Repository scala-steward-org/scala-steward, pull requests merged in 2019-03, with the labels that each got.

#334 Implement withUserInfo as Optional[Uri, UserInfo]
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/dependency/DependencyService.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/uri.scala
  modules/core/src/test/scala/org/scalasteward/core/util/uriTest.scala
  project/Dependencies.scala
Labels: refactoring

#338 Use Uri instead of String for GitHub URLs
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/github/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/github/http4s/Http4sUrl.scala
  modules/core/src/main/scala/org/scalasteward/core/util/uri.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/GithubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/UrlTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/http4s/http4sUrlTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/util/uriTest.scala
Labels: refactoring

#340 Parse githubApiHost as Uri
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  scripts/run.sh
Labels: refactoring

#337 Ability to inject environment variables to firejail
  README.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: enhancement

#342 Test GitHubApiAlg via Http4sGitHubApiAlg
  build.sbt
  modules/core/src/test/scala/org/scalasteward/core/github/GithubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlgTest.scala
  project/Dependencies.scala
Labels: testing

#359 Always use Config.gitHubLogin in PR body
  modules/core/src/main/scala/org/scalasteward/core/github/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/github/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/github/data/NewPullRequestDataTest.scala
Labels: enhancement

#360 Add cwd parameter in MockProcessAlg.exec to MockState
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: testing

#361 Add algebra for cloning and syncing GitHub repos
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/dependency/DependencyService.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/github/GitHubRepoAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/GitHubRepoAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/GithubPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: refactoring

#373 Pass repo to the function for modifying requests
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/test/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlgTest.scala
Labels: refactoring
