Repository scala-steward-org/scala-steward, pull requests merged in 2019-12, with the labels that each got.

#1123 Do not grow line buffer in slurp unbounded
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
Labels: bug

#1125 Add RawUpdate type for decoding the output of stewardUpdates
  modules/core/src/main/scala/org/scalasteward/core/data/RawUpdate.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: refactoring

#1127 Update coursier, coursier-cats-interop to 2.0.0-RC5-3
  project/Dependencies.scala
Labels: dependency-update

#1129 Do not use RepoCacheRepository in SbtAlg
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
Labels: enhancement

#1132 Update scalafmt-core to 2.3.1
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/RepositoryResponse.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
Labels: dependency-update

#1134 Do not select a dynamic version as next version
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1135 Add gitstalk link for @scala-steward
  README.md
Labels: administration

#1137 Inline SbtAlg.getOriginalDependencies
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: refactoring

#1138 Add getSbtDependency and getScalafmtDependency
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
Labels: refactoring

#1140 Remove more dead code in sbt package object
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
Labels: refactoring

#1142 Take groupId changes in checkForUpdates into account
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
Labels: bug

#1143 Add order for Preview and B Alpha values on Version ordering
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1145 Update sbt-scalafmt to 2.3.0
  project/plugins.sbt
Labels: dependency-update

#1146 Update scalafmt-core to 2.3.2
  .scalafmt.conf
Labels: dependency-update

#1147 Allow bump from dynamic version to greater release version
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: bug

#1148 Do not select versions with a hyphen
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1149 Allow to mark version ranges as bad
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: enhancement

#1150 Split UpdateAlg so that it can be used in SbtAlg
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
Labels: refactoring

#1151 Replace withTemporarySbtDependency with findUpdate
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: refactoring

#1152 Only select versions that start with a letter or digit
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1153 Set TTL of Coursier's FileCache to 1 hour
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
Labels: enhancement

#1154 Update sbt-native-packager to 1.5.2
  project/plugins.sbt
Labels: dependency-update

#1155 Refactorings in CoursierAlg
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: refactoring

#1159 Move Update.searchTerms to UpdateHeuristic
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
Labels: refactoring

#1161 Move Update.removeCommonSuffix to UpdateHeuristic
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
Labels: refactoring

#1164 Publish scala-steward-core jar
  .travis.yml
  project/plugins.sbt
Labels: build

#1167 Update scalacheck to 1.14.3
  project/Dependencies.scala
Labels: dependency-update

#1166 Update sbt to 1.3.5
  project/build.properties
Labels: dependency-update

#1168 Add source URLs to Scaladocs
  build.sbt
Labels: documentation

#1169 Don't use Update.Group.artifactId for sorting updates
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
Labels: refactoring

#1170 Remove unnecessary parameter
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: refactoring

#1172 Rename Update.artifactId to mainArtifactId
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
Labels: refactoring

#1174 Check updates for all crossScalaVersions
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/ArtifactId.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
  modules/core/src/main/scala/org/scalasteward/core/data/RawUpdate.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/show.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/ExampleTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/showTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: enhancement

#1176 Simplify pruning logic
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: enhancement

#1177 Update cats-kernel-laws to 2.1.0
  project/Dependencies.scala
Labels: dependency-update

#1179 Ignore dependency configurations in PruningAlg
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
Labels: enhancement

#1180 Use sbt's logger instead of println in tasks
  modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: enhancement

#1181 Add StewardAlg.steward that combines pruning logic
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: refactoring

#1182 Mark old guava versions as bad
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1183 Move findUpdates to UpdateAlg
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/ArtifactId.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
Labels: refactoring

#1185 Use traverseFilter in UpdateAlg and other refactorings
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
Labels: refactoring

#1186 Update coursier, coursier-cats-interop to 2.0.0-RC5-4
  project/Dependencies.scala
Labels: dependency-update

#1189 Update Scala to 2.13.1
  .travis.yml
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
Labels: dependency-update

#1190 Remove dead code in KeyValueStore
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/KeyValueStore.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
Labels: refactoring

#1191 Parallelize some IO operations in RepoCacheAlg
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
Labels: refactoring

#1194 Edit files that end with .sbt.shared
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
Labels: enhancement

#1192 Remove sbt and scalafmt version from RepoCache
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCache.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
Labels: refactoring

#1195 Update sbt to 1.3.6
  project/build.properties
Labels: dependency-update

#1196 Include dependencies in Update
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/ArtifactId.scala
  modules/core/src/main/scala/org/scalasteward/core/data/CrossDependency.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
  modules/core/src/main/scala/org/scalasteward/core/data/RawUpdate.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/data/SbtVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/data/ScalaVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
  modules/core/src/test/scala/org/scalasteward/core/data/ExampleTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/showTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: enhancement

#1197 Add --cache-ttl CLI option
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  scripts/run.sh
Labels: enhancement

#1198 Add FilterAlg.isIgnoredGlobally again
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: bug

#1199 Ocado is using Steward!
  README.md
Labels: administration

#1200 Also update sbt if it is in Update.Group
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
Labels: bug

#1201 Fix duplicated artifactIds in PR titles
  modules/core/src/main/scala/org/scalasteward/core/update/show.scala
  modules/core/src/test/scala/org/scalasteward/core/update/showTest.scala
Labels: bug

#1202 Parallelize UpdateAlg.findUpdate
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: refactoring

#1203 Update sbt-ci-release to 1.5.0
  project/plugins.sbt
Labels: dependency-update

#1204 Use Uri as return type of CoursierAlg.getArtifactUrl
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: bug

#1205 Tweak version ordering so that it is more similar to Coursier's
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement
