Repository scala-steward-org/scala-steward, pull requests merged in 2019-07, with the labels that each got.

#648 Elevate pre release semver
  modules/core/src/main/scala/org/scalasteward/core/model/SemVer.scala
  modules/core/src/test/scala/org/scalasteward/core/model/SemVerTest.scala
Labels: bug

#650 Split getRepoConfig into readRepoConfig{,OrDefault}
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: refactoring

#651 Add link to GH search for example Mergify rules
  docs/faq.md
Labels: documentation

#660 Update running.md with --vcs-api-host --vcs-login flags
  docs/running.md
Labels: documentation

#647 Bitbucket support
  modules/core/src/main/scala/org/scalasteward/core/application/SupportedVCS.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/CreatePullRequestRequest.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Page.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/RepositoryResponse.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/authentication.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/json.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/JsonCodecTest.scala
Labels: enhancement

#665 Add ability to propose sbt version update
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/data/SbtVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/sbtTest.scala
Labels: enhancement

#673 Add SbtAlg.getSbtVersion
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: refactoring

#683 Update run documentation
  docs/running.md
Labels: documentation

#692 Rename DependencyService to RepoCacheAlg and store sbt versions
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/model/Dependency.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/json/JsonPullRequestRepo.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCache.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/json/JsonRepoCacheRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/json/RepoStore.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/data/ArtificialProject.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
  modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
  modules/core/src/main/scala/org/scalasteward/core/update/splitter.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/data/ArtificialProjectTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
Labels: enhancement

#693 Cope with whitespace in build.properties
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
Labels: enhancement

#699 Include sbt in update check
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/sbtTest.scala
Labels: enhancement

#703 Incorporate changes to FAQ by @nafg
  README.md
  docs/faq.md
Labels: documentation

#706 Use nextVersion when looking for existing PRs
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/json/JsonPullRequestRepo.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
Labels: bug

#708 Log executed commands
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
Labels: enhancement

#710 Specify {ROOT_,}LOG_LEVEL as a poor man's documentation
  scripts/run.sh
Labels: documentation

#714 - added SCROLL
  repos.md
Labels: repos-update

#671 Add markup to ignore lines
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: enhancement

#718 Add Change datatype
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
  modules/core/src/main/scala/org/scalasteward/core/util/Change.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/editTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/ChangeTest.scala
Labels: refactoring

#724 Update PRs only if there are conflicts with the base branch
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: enhancement

#725 Set 1.3.0-RC3 as latest sbt RC for 1.3.0
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/sbtTest.scala
Labels: dependency-update

#728 Update sbt-updates to 0.4.2
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
Labels: dependency-update

#729 Show "labels:" in PR body only if there are labels
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
Labels: bug

#731 Add my repo
  repos.md
Labels: repos-update

#736 shouldBeReset: run Git commands only if needed
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: refactoring

#739 Log in DEBUG which files we're writing
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/LoggerTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
Labels: enhancement

#757 Merge instead of reset/force-push to resolve conflicts
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
Labels: enhancement

#767 Document scala-steward:off|on markers.
  docs/repo-specific-configuration.md
Labels: documentation

#769 Sign merge commits
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: enhancement

#770 Replace scalaz-nio with zio-nio
  repos.md
Labels: repos-update
