Repository scala-steward-org/scala-steward, pull requests merged in 2019-10, with the labels that each got.

#1012 Set dependencyUpdatesFailBuild to false
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: bug

#1013 Prevent updates to commons-collections 20040102.233541
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1015 Treat alpha and beta versions as pre-releases
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: bug

#1016 Use a single Blocker for the whole application
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
Labels: refactoring

#1019 Introduce Version.Component to improve Order[Version]
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1024 Remove catch all case in getNewerGroupId
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
Labels: refactoring

#1029 Simplify FilterAlg.badVersions
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1033 Only consider versions with pre-release identifiers as pre-releases
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1034 Update sbt-scalafmt to 2.0.7
  project/plugins.sbt
Labels: dependency-update

#1039 Update sbt to 1.3.3
  project/build.properties
Labels: dependency-update

#1036 Update coursier, coursier-cats-interop to 2.0.0-RC4
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/RepositoryResponse.scala
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/GitHubRepoAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/UrlTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/uriTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/PullRequestOutTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/RepoOutTest.scala
  project/Dependencies.scala
Labels: dependency-update

#1040 Update monocle-core to 2.0.0
  project/Dependencies.scala
Labels: dependency-update

#1041 Update scalatest to 3.1.0-RC3
  project/Dependencies.scala
Labels: dependency-update

#1042 Update sbt-updates to 0.5.0
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
Labels: dependency-update

#1044 Resolve POMs of sbt plugins
  modules/core/src/main/resources/StewardPlugin.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
Labels: enhancement

#1045 Update log4cats-slf4j to 1.0.1
  project/Dependencies.scala
Labels: dependency-update

#1047 Remove Sync dependency from EditAlg
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
Labels: refactoring

#1049 add heuristic taking into account org type for short group ids
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: enhancement

#793 Erroneous Cats update
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: bug

#1051 Some small refactorings
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
Labels: refactoring

#1050 add support for limiting updates through config
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/data/ProcessResult.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: enhancement

#1054 Update scalafmt-core to 2.2.1
  .scalafmt.conf
Labels: dependency-update

#1059 Update sbt-scalafmt to 2.2.0
  project/plugins.sbt
Labels: dependency-update

#1058 Update circe-generic, circe-literal, ... to 0.12.3
  project/Dependencies.scala
Labels: dependency-update

#1055 Add takeUntil stream combinator
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
Labels: refactoring

#1061 Ammonite support
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: enhancement

#1062 Update sbt-scalafmt to 2.2.1
  project/plugins.sbt
Labels: dependency-update

#1063 Update coursier, coursier-cats-interop to 2.0.0-RC4-1
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  project/Dependencies.scala
Labels: dependency-update

#1064 Ignore separators when comparing versions
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1069 Use CompileOps.string instead of CompileOps.foldMonoid
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
Labels: refactoring

#1070 Add "ReleaseNotes" as possible filename for release notes
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
Labels: enhancement

#1072 Update sbt-scalafix to 0.9.8
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update
