Repository scala-steward-org/scala-steward, pull requests merged in 2019-11, with the labels that each got.

#1073 Update scalafmt-core to 2.2.2
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/RepositoryResponse.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/JsonCodecTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/ExampleTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/showTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/uriTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/RepoTest.scala
Labels: dependency-update

#1075 Extract parseFiniteDuration from the ArgParser instance
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
Labels: refactoring

#1076 Test GitAlg.isMerged in test of mergeTheirs
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
Labels: testing

#1077 Do not use Option for repoUrl parameters in VCSExtraAlg
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
Labels: refactoring

#1079 Update fs2-core to 2.1.0
  project/Dependencies.scala
Labels: dependency-update

#1081 Add in-memory cache to HttpExistenceClient
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  project/Dependencies.scala
Labels: enhancement

#1074 Run self checks at program start
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
Labels: enhancement

#1082 default to hompeage on coursierAlg if url starts with git@
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
Labels: enhancement

#1083 Add "release-$version" as possible tag for diffs and release notes
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
Labels: enhancement

#1084 Update sbt-header to 5.3.0
  project/plugins.sbt
Labels: dependency-update

#1085 Add CHANGES as basename of possible changelog filenames
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
Labels: enhancement

#1086 Extract getScmUrlOrHomePage
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
Labels: refactoring

#1089 Update coursier, coursier-cats-interop to 2.0.0-RC5-1
  project/Dependencies.scala
Labels: dependency-update

#1091 Update coursier, coursier-cats-interop to 2.0.0-RC5-2
  project/Dependencies.scala
Labels: dependency-update

#1092 CoursierAlg: Fetch ivy.xml files from sbt-plugin-releases
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
Labels: enhancement

#1094 Treat 'AM' as pre-release identifier
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1095 Update sbt-native-packager to 1.5.0
  project/plugins.sbt
Labels: dependency-update

#1096 Replace our own evalFilter with fs2's
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
Labels: refactoring

#1097 Mark Scala.js 0.6.30 as bad
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1098 Update sbt-scoverage to 1.6.1
  project/plugins.sbt
Labels: dependency-update

#1101 Clean up FilterAlg.badVersions
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: refactoring

#1103 Update sbt to 1.3.4
  project/build.properties
Labels: dependency-update

#1106 Update sbt-native-packager to 1.5.1
  project/plugins.sbt
Labels: dependency-update

#1108 Update sbt-scalafix to 0.9.9
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1107 Move the decisions if a PR should be updated closer together
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: refactoring

#1109 Update sbt-tpolecat to 0.1.9
  project/plugins.sbt
Labels: dependency-update

#1111 Update sbt-header to 5.3.1
  project/plugins.sbt
Labels: dependency-update

#1112 Revert "Use 2.12 for Scalafix migrations"
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: enhancement

#1113 Update sbt-tpolecat to 0.1.10
  project/plugins.sbt
Labels: dependency-update

#1114 Move StewardPlugin in new plugin subproject
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: build

#1116 New StewardPlugin tasks, attempt 2
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/data/ArtificialProject.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/data/ArtificialProjectTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: enhancement

#1117 Update http4s-async-http-client, ... to 0.21.0-M6
  project/Dependencies.scala
Labels: dependency-update

#1118 Update scalatest to 3.1.0
  project/Dependencies.scala
Labels: dependency-update

#1119 Remove repo in NurtureAlg even if there is an error
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: enhancement

#1122 Update sbt-scalafix to 0.9.11
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update
