Repository scala-steward-org/scala-steward, pull requests merged in 2019-02, with the labels that each got.

#297 Do not repeat commands in getUpdatesForRepo
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
Labels: refactoring

#300 Ignore lines that contain "mimaPreviousArtifacts"
  modules/core/src/main/scala/org/scalasteward/core/model/Update.scala
  modules/core/src/test/scala/org/scalasteward/core/model/UpdateTest.scala
Labels: bug

#301 Ignore updates via a repo-specific .scala-steward.conf file
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  project/Dependencies.scala
Labels: enhancement

#303 Test FileAlg.{deleteForce, readFile, writeFile}
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
Labels: testing

#318 Fix docker volume mounting in README.
  README.md
Labels: documentation

#321 Implement attemptLog_ directly without attemptLog
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
Labels: refactoring

#326 Test FileAlg.removeTemporarily
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
Labels: testing

#328 Move constraints on F[_] to the class level
  modules/core/src/main/scala/org/scalasteward/core/dependency/DependencyService.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: refactoring
