Repository scala-steward-org/scala-steward, pull requests merged in 2019-09, with the labels that each got.

#878 do not force push as it might overwrite other changes
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/GitHubRepoAlgTest.scala
Labels: enhancement

#913 Replace LoggerAlg with LoggerOps
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/LogAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
Labels: refactoring

#914 Revert "do not force push as it might overwrite other changes"
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/GitHubRepoAlgTest.scala
Labels: bug

#925 Ignore errors in memoizedGetDependencies
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: bug

#933 Add setup to run on Docker w/ Bitbucket
  docs/running.md
Labels: documentation

#934 Removed repo barambani/http4s-extend
  repos.md
Labels: repos-update

#935 Remove dead code
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
Labels: refactoring

#937 Update Scala to 2.12.10
  .travis.yml
Labels: dependency-update

#938 Fetch only default branch when syncing the fork
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/GitHubRepoAlgTest.scala
Labels: enhancement

#945 Use a common implementation for JSON repositories
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/json/JsonPullRequestRepo.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/json/PullRequestStore.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/json/JsonRepoCacheRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/json/RepoStore.scala
  modules/core/src/main/scala/org/scalasteward/core/update/json/JsonUpdateRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/update/json/UpdateStore.scala
  modules/core/src/main/scala/org/scalasteward/core/util/JsonKeyValueStore.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: refactoring

#946 Add Coursier to Travis cache
  .travis.yml
Labels: build

#947 Add basic JsonKeyValueStore test
  modules/core/src/test/scala/org/scalasteward/core/util/JsonKeyValueStoreTest.scala
Labels: testing

#951 Print banner at start of application
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
Labels: enhancement

#955 Introduce KeyValueStore
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/json/JsonPullRequestRepo.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/json/PullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/KeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/json/JsonRepoCacheRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateRepository.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/JsonKeyValueStoreTest.scala
Labels: refactoring

#623 Use logger.error instead of println
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
Labels: refactoring

#963 Rename UpdateService to UpdateAlg
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
Labels: refactoring

#970 De-duplicate error in FiniteDuration parser
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  scripts/run.sh
Labels: refactoring

#972 Update repos.md
  repos.md
Labels: repos-update

#978 Automatically exclude dependencies from update check
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/update/ExcludeAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
Labels: enhancement

#985 Use 2.12 for Scalafix migrations
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: enhancement

#991 Move repos.md to scala-steward-org/repos
  README.md
  repos.md
  scripts/run.sh
  scripts/sort-repos.sh
Labels: repos-update

#964 Update scalafix for scalatest
  modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
Labels: scalafix-migration

#996 simulacrum has a new groupid
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
Labels: enhancement

#997 Do not refresh caches of failing repos
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
Labels: enhancement

#1001 Do not mention @scala-steward in the PR body
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#1009 Prevent updates to a pre-release of another series
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: bug
