Repository scala-steward-org/scala-steward, pull requests merged in 2019-08, with the labels that each got.

#781 Added labra/shaclex
  repos.md
Labels: repos-update

#783 Allow using a custom base image for docker builds
  build.sbt
Labels: build

#786 Add discipline-specs2 and discipline-scalatest
  repos.md
Labels: repos-update

#784 Clean up process.slurp
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
Labels: refactoring

#787 Add NomadBlacky/scala_examples and scaladog
  repos.md
Labels: repos-update

#789 Update Scala to 2.12.9
  .travis.yml
Labels: dependency-update

#791 Clean up UpdateHeuristic
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: refactoring

#795 handle "merged" status for a Gitlab MR. Fix #743
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestState.scala
Labels: bug

#805 Add Play SOAP repository
  repos.md
Labels: repos-update

#802 Update the url of scalafix rule for cats v1.0.0
  modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
Labels: bug

#812 Extract crossName from libraryDependenciesAsJson
  modules/core/src/main/resources/StewardPlugin.scala
Labels: refactoring

#816 Update latest scalafmt version to 2.0.1
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/scalafmtTest.scala
Labels: dependency-update

#817 Use latestScalafmtVersion in test
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/scalafmtTest.scala
Labels: refactoring

#799 Add pathikrit/dijon
  repos.md
Labels: repos-update

#822 Add ceedubs/irrec
  repos.md
Labels: repos-update

#823 Split refreshCache into two functions
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
Labels: refactoring

#825 Reformat config snippet for ignoring updates
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: refactoring

#831 Prevent duplicated sbt dependencies
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
Labels: bug

#835 Simplify getArtifactIdUrlMapping
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
Labels: refactoring

#836 Add update state UpdateRejectedByConfig
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
  modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
Labels: enhancement

#840 Allow env-var values to contain equals signs
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
Labels: enhancement

#841 Use env var instead of hardcoded temporary .jvmopts
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
  scripts/run.sh
Labels: refactoring

#844 Use sbt's scalaBinaryVersion for scalafmtDependency
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/UtilTest.scala
Labels: refactoring

#845 Remove scalaBinaryVersion from temporary scalafmt dependency.
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: bug

#846 Only look into regular and non-symlink files in findFilesContaining
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
Labels: enhancement

#847 scalafmt-core prior to 2.0.0-RC2 used a different groupId
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
Labels: bug

#854 Always run Scalafix migrations for main and test sources
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/Migration.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: enhancement

#856 Fix compile error with sbt 0.13
  modules/core/src/main/resources/StewardPlugin.scala
Labels: bug
