Repository scala-steward-org/scala-steward, pull requests merged in 2020-04, with the labels that each got.

#1390 Update http4s-async-http-client, ... to 0.21.3
  project/Dependencies.scala
Labels: dependency-update

#1392 Fix round-tripping of PullRequestsFrequency codec
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestFrequency.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestFrequencyTest.scala
Labels: bug

#1383 Add repo specific conf link to PR body
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#1395 Revert "fix#1376: markdown files considered for library pattern updates"
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
Labels: bug

#1396 Update sbt-header to 5.5.0
  project/plugins.sbt
Labels: dependency-update

#1397 Update sbt-scalafmt to 2.3.4
  project/plugins.sbt
Labels: dependency-update

#1298 Support custom group migrations
  modules/core/src/main/resources/group-migrations.conf
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/update/GroupMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/update/GroupMigrationsTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
  project/Dependencies.scala
Labels: enhancement

#1398 Update sbt-scalafix to 0.9.14
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1399 Update sbt to 1.3.10
  project/build.properties
Labels: dependency-update

#1400 Update coursier, coursier-cats-interop to 2.0.0-RC6-12
  project/Dependencies.scala
Labels: dependency-update

#1402 Update sbt-wartremover, wartremover to 2.4.6
  project/plugins.sbt
Labels: dependency-update

#1401 Update cats-effect to 2.1.3
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  project/Dependencies.scala
Labels: dependency-update

#1404 Update sbt-wartremover to 2.4.7
  project/plugins.sbt
Labels: dependency-update

#1405 Update sbt-header to 5.6.0
  project/plugins.sbt
Labels: dependency-update

#1408 Update sbt-scalafix to 0.9.15
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1409 Update sbt-ci-release to 1.5.3
  project/plugins.sbt
Labels: dependency-update

#1410 Update refined, refined-cats, ... to 0.9.14
  project/Dependencies.scala
Labels: dependency-update

#1412 Update coursier, coursier-cats-interop to 2.0.0-RC6-13
  project/Dependencies.scala
Labels: dependency-update

#1407 check for all artifact URLs return by coursier, if they exists.
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: enhancement

#1416 Update http4s-async-http-client, ... to 0.21.4
  project/Dependencies.scala
Labels: dependency-update

#1417 Mark org.scala-lang:scalap as Scala dependency
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1406 Introduce an option in the repository config for the file extension
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: enhancement
