Repository scala-steward-org/scala-steward, pull requests merged in 2020-06, with the labels that each got.

#1464 Update coursier, coursier-cats-interop to 2.0.0-RC6-20
  project/Dependencies.scala
Labels: dependency-update

#1461 Update sbt to 1.3.11
  project/build.properties
Labels: dependency-update

#1463 Update sbt to 1.3.12
  project/build.properties
Labels: dependency-update

#1465 Update sbt-native-packager to 1.7.3
  project/plugins.sbt
Labels: dependency-update

#1466 Update sbt-tpolecat to 0.1.12
  project/plugins.sbt
Labels: dependency-update

#1467 Update coursier, coursier-cats-interop to 2.0.0-RC6-21
  project/Dependencies.scala
Labels: dependency-update

#1451 docs: Add Avast to community list
  README.md
  docs/running.md
Labels: administration, documentation

#1475 Update fs2-core to 2.4.0
  project/Dependencies.scala
Labels: dependency-update

#1476 Update sbt-scalafix to 0.9.17
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1477 Update fs2-core to 2.4.1
  project/Dependencies.scala
Labels: dependency-update

#1479 Update fs2-core to 2.4.2
  project/Dependencies.scala
Labels: dependency-update

#1482 Update monocle-core to 2.0.5
  project/Dependencies.scala
Labels: dependency-update

#1484 Fix deleteForce to also delete dangling symlinks
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
Labels: bug

#1480 Fallback to credentials for sbt 1.2.x
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: bug

#1485 Update case-app to 2.0.1
  project/Dependencies.scala
Labels: dependency-update

#1490 Update scalatest to 3.2.0
  project/Dependencies.scala
Labels: dependency-update

#1494 Make --default-repo-conf an optional argument
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  scripts/run.sh
Labels: refactoring

#1495 Rename plugin and mill sbt projects to sbt-plugin and mill-plugin
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/mill-plugin/src/main/scala/org/scalasteward/mill/plugin/StewardPlugin.scala
  modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala
Labels: refactoring

#1496 Update mill-scalalib to 0.7.3
  build.sbt
Labels: dependency-update

#1497 Fix reference to the root pkg of the mill-plugin project
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
Labels: bug

#1498 Fix loading of scala-steward-mill-plugin in MillAlg
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
Labels: bug

#1500 Update case-app to 2.0.2
  project/Dependencies.scala
Labels: dependency-update

#1503 Update http4s-async-http-client, ... to 0.21.5
  project/Dependencies.scala
Labels: dependency-update

#1502 Adding a scalafix rule for sbt-guardrail 0.59.0+
  modules/core/src/main/resources/scalafix-migrations.conf
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
Labels: scalafix-migration

#1505 Update case-app to 2.0.3
  project/Dependencies.scala
Labels: dependency-update

#1493 Update sbt-assembly to 0.15.0
  project/plugins.sbt
Labels: dependency-update

#1506 Update sbt-tpolecat to 0.1.13
  project/plugins.sbt
Labels: dependency-update

#1509 Update http4s-async-http-client, ... to 0.21.6
  project/Dependencies.scala
Labels: dependency-update

#1510 Add Scalafix migration for http4s 0.21.5
  modules/core/src/main/resources/scalafix-migrations.conf
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
Labels: scalafix-migration
