Repository scala-steward-org/scala-steward, pull requests merged in 2020-11, with the labels that each got.

#1705 Run sbt without -batch and -no-colors options
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
Labels: enhancement

#1706 Update sbt to 1.4.2
  project/build.properties
Labels: dependency-update

#1707 Update coursier, coursier-cats-interop to 2.0.6
  project/Dependencies.scala
Labels: dependency-update

#1708 Do not put sbt in offline mode
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/command.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
Labels: enhancement

#1709 Set sbt properties to disable colors and the supershell
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
Labels: enhancement

#1711 Update sbt-ci-release to 1.5.4
  project/plugins.sbt
Labels: dependency-update

#1712 Close standard input of processes created by slurp
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
Labels: bug

#1713 Pass sbt properties as parameters
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
Labels: enhancement

#1715 Update sbt-scalafix to 0.9.23
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1714 Use GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/clean.yml
  .mergify.yml
  .travis.yml
  README.md
  build.sbt
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  project/plugins.sbt
Labels: build

#1717 GH Actions: use nicer names for the publishing steps
  .github/workflows/ci.yml
  build.sbt
Labels: build

#1718 Update scalacheck to 1.15.1
  project/Dependencies.scala
Labels: dependency-update

#1720 Replace Sync with MonadThrow in VCSSelection and *ApiAlg
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
Labels: refactoring

#1719 Change default value of --disable-sandbox
  build.sbt
  docs/running.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  scripts/run.sh
Labels: enhancement

#1722 Test parsing RepoConfig with unknown PullRequestUpdateStrategy
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: testing

#1721 Do not pass Config implicitly
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/WorkspaceAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/ArtifactMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: refactoring

#1724 Fix setting enableSandbox from Cli.Args
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
Labels: bug

#1725 Improve SupportedVCS.parse
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/SupportedVCS.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
Labels: refactoring

#1726 Update scalatest-funsuite, ... to 3.2.3
  project/Dependencies.scala
Labels: dependency-update

#1728 Test GitAlg.containsChanges
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
Labels: testing

#1729 Update fs2-core, fs2-io to 2.4.5
  project/Dependencies.scala
Labels: dependency-update

#1730 Update sbt-wartremover, wartremover to 2.4.13
  project/plugins.sbt
Labels: dependency-update

#1731 Update sbt-tpolecat to 0.1.15
  project/plugins.sbt
Labels: dependency-update

#1732 Remove http4s packag/prefix from VCSApiAlg implementations
  docs/running.md
  modules/core/src/main/scala/org/scalasteward/core/application/SupportedVCS.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/CreatePullRequestRequest.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/Page.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/RepositoryResponse.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/authentication.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/json.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/authentication.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/authentication.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/JsonCodecTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/github/authenticationTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Labels: refactoring

#1733 Add links to GitHub's API documentation
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
Labels: documentation

#1734 Do not use gpg2 with sbt-ci-release
  .github/workflows/ci.yml
  build.sbt
Labels: build

#1735 Use next version when looking for artifact URLs
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
Labels: enhancement

#1737 Update sbt-doctest to 0.9.8
  project/plugins.sbt
Labels: dependency-update

#1739 Update http4s-circe, http4s-client, ... to 0.21.9
  project/Dependencies.scala
Labels: dependency-update

#1743 Update discipline-scalatest to 2.1.0
  project/Dependencies.scala
Labels: dependency-update

#1744 Extract PR number from URL only if absent in PullRequestData
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestNumber.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Labels: refactoring

#1746 Update refined, refined-cats, ... to 0.9.18
  project/Dependencies.scala
Labels: dependency-update

#1747 Update sbt to 1.4.3
  project/build.properties
Labels: dependency-update

#1750 Update sbt-github-actions to 0.9.5
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependency-update

#1752 Update coursier, coursier-cats-interop to 2.0.7
  project/Dependencies.scala
Labels: dependency-update

#1751 Support post update hooks
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/PostUpdateHook.scala
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
Labels: enhancement

#1754 Post-update hooks: do not run scalafmt in a sandbox
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/PostUpdateHook.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
Labels: enhancement

#1755 Mill: extract artifact names with and without binary suffix
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillDepParserTest.scala
  modules/mill-plugin/src/main/scala/org/scalasteward/mill/plugin/StewardPlugin.scala
Labels: enhancement

#1756 Update kind-projector to 0.11.1
  project/Dependencies.scala
Labels: dependency-update

#1757 Update http4s-circe, http4s-client, ... to 0.21.11
  project/Dependencies.scala
Labels: dependency-update

#1758 Run firejail with --quiet option
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  scripts/run.sh
Labels: enhancement

#1762 Update sbt to 1.4.4
  project/build.properties
Labels: dependency-update

#1764 Update fs2-core, fs2-io to 2.4.6
  project/Dependencies.scala
Labels: dependency-update

#1767 Add bad versions of commons-codec and commons-io
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1769 Update http4s-circe, http4s-client, ... to 0.21.13
  project/Dependencies.scala
Labels: dependency-update

#1770 Update cats-core, cats-laws to 2.3.0
  project/Dependencies.scala
Labels: dependency-update

#1768 Update mill-scalalib to 0.9.3
  build.sbt
  project/Dependencies.scala
Labels: dependency-update

#1771 Fix tests on macOS
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
Labels: testing

#1772 Update sbt-scalafix to 0.9.24
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1773 Update cats-effect to 2.3.0
  project/Dependencies.scala
Labels: dependency-update

#1105 Fixed typo
  README.md
Labels: administration

#1763 Add FileGitAlg
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/package.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: refactoring

#1766 support GitHub Apps
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApp.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubAppApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubAuthAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/InstallationOut.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/RepositoriesOut.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/TokenOut.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  project/Dependencies.scala
Labels: enhancement

#1774 Do not replace a substring in another version
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: bug

#1775 Add signingKey to git.Author
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/git/Author.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
Labels: enhancement

#1776 Don't replace version numbers in comments
  modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: enhancement
