Repository scala-steward-org/scala-steward, pull requests merged in 2020-03, with the labels that each got.

#1352 Update cats-effect to 2.1.2
  project/Dependencies.scala
Labels: dependency-update

#1354 Mark com.nequissimus:sort-imports:36845576 as an invalid version.
  .gitignore
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1355 Update refined, refined-cats, ... to 0.9.13
  project/Dependencies.scala
Labels: dependency-update

#1356 Update monocle-core to 2.0.4
  project/Dependencies.scala
Labels: dependency-update

#1357 Update sbt-scalafmt to 2.3.2
  project/plugins.sbt
Labels: dependency-update

#1358 Use PosInt as type for updates.limit
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: enhancement

#1360 Update case-app to 2.0.0-M14
  project/Dependencies.scala
Labels: dependency-update

#1362 Update sbt-native-packager to 1.6.2
  project/plugins.sbt
Labels: dependency-update

#1364 Update case-app to 2.0.0-M15
  project/Dependencies.scala
Labels: dependency-update

#1365 Update case-app to 2.0.0-M16
  project/Dependencies.scala
Labels: dependency-update

#1366 Update circe-config to 0.8.0
  project/Dependencies.scala
Labels: dependency-update

#1367 Update sbt-scalafix to 0.9.12
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1368 Update fs2-core to 2.3.0
  project/Dependencies.scala
Labels: dependency-update

#1369 Update coursier, coursier-cats-interop to 2.0.0-RC6-11
  project/Dependencies.scala
Labels: dependency-update

#1363 Update sbt-native-packager to 1.7.0
  project/plugins.sbt
Labels: dependency-update

#1372 Update http4s-async-http-client, ... to 0.21.2
  project/Dependencies.scala
Labels: dependency-update

#1373 add context to json paring errors
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
Labels: enhancement

#1250 Add the ability to use default reviewers to bitbucket server
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Json.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: enhancement

#1378 Update sbt-explicit-dependencies to 0.2.13
  project/plugins.sbt
Labels: dependency-update

#1361 Support sbt credentials for coursier
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Resolver.scala
  modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: enhancement

#1381 Update scala version
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: enhancement

#1385 Update sbt to 1.3.9
  project/build.properties
Labels: dependency-update

#1384 Make RepoConfig.updatePullRequests optional
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: refactoring

#1386 Update sbt-scalafix to 0.9.13
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update
