Repository scala-steward-org/scala-steward, pull requests merged in 2020-05, with the labels that each got.

#1420 Update coursier, coursier-cats-interop to 2.0.0-RC6-14
  project/Dependencies.scala
Labels: dependency-update

#1422 Update sbt-native-packager to 1.7.1
  project/plugins.sbt
Labels: dependency-update

#1419 add scalafix rule for scalaz 7.3
  modules/core/src/main/resources/scalafix-migrations.conf
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
Labels: scalafix-migration

#1424 Update sbt-wartremover to 2.4.8
  project/plugins.sbt
Labels: dependency-update

#1425 Update coursier, coursier-cats-interop to 2.0.0-RC6-15
  project/Dependencies.scala
Labels: dependency-update

#1427 Update scalatest to 3.1.2
  project/Dependencies.scala
Labels: dependency-update

#1428 Update sbt-native-packager to 1.7.2
  project/plugins.sbt
Labels: dependency-update

#1430 Update log4cats-slf4j to 1.1.1
  project/Dependencies.scala
Labels: dependency-update

#1429 Prepare support for other build systems
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/BuildSystemAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/BuildSystemDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/sbt/command.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/sbt/data/SbtVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/sbt/data/ScalaVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/sbt/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildsystem/BuildSystemDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildsystem/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildsystem/sbt/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#1431 Update Travis Configuration
  .travis.yml
Labels: build

#1433 Do not use hardcoded paths in BuildSystemDispatcherTest
  modules/core/src/test/scala/org/scalasteward/core/buildsystem/BuildSystemDispatcherTest.scala
Labels: refactoring

#1434 Update sbt-scalafmt to 2.4.0
  project/plugins.sbt
Labels: dependency-update

#1435 Update coursier, coursier-cats-interop to 2.0.0-RC6-16
  project/Dependencies.scala
Labels: dependency-update

#1436 Show env vars in slurp's error messages
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
Labels: enhancement

#1438 Update Scala to 2.13.2 and 2.12.11
  .travis.yml
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
Labels: dependency-update

#1426 Update scalafmt-core to 2.5.2
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/application/SupportedVCS.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Page.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/RepositoryResponse.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/BuildSystemDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/WorkspaceAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/GroupMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/Details.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/data/SemVerTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/UrlTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/stringTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: dependency-update

#1441 human readable format for `UpdateState`
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: enhancement

#1432 Maven support, take two
  build.sbt
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/BuildSystemDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/maven/command.scala
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/maven/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/buildsystem/BuildSystemDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildsystem/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildsystem/maven/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  project/Dependencies.scala
  repos.md
Labels: enhancement

#1443 Update atto-core to 0.7.2
  project/Dependencies.scala
Labels: dependency-update

#1444 Update atto-core to 0.8.0
  project/Dependencies.scala
Labels: dependency-update

#1445 Remove duplicated resolvers in MavenAlg
  modules/core/src/main/scala/org/scalasteward/core/buildsystem/maven/MavenAlg.scala
Labels: bug

#1446 Update coursier, coursier-cats-interop to 2.0.0-RC6-17
  project/Dependencies.scala
Labels: dependency-update

#1448 Update better-files to 3.9.1
  project/Dependencies.scala
Labels: dependency-update

#1449 Rename BuildSystem to BuildTool
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/command.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/command.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/data/SbtVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/data/ScalaVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/GroupMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/gitTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/GroupMigrationsTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: refactoring

#1450 Update coursier, coursier-cats-interop to 2.0.0-RC6-18
  project/Dependencies.scala
Labels: dependency-update

#1455 Update coursier, coursier-cats-interop to 2.0.0-RC6-19
  project/Dependencies.scala
Labels: dependency-update

#1456 Update scalafmt-core to 2.5.3
  .scalafmt.conf
Labels: dependency-update

#1457 Update sbt-scalafix to 0.9.16
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1458 Update commons-io to 2.7
  project/Dependencies.scala
Labels: dependency-update

#1459 Update case-app to 2.0.0
  project/Dependencies.scala
Labels: dependency-update

#1462 Update sbt-wartremover to 2.4.9
  project/plugins.sbt
Labels: dependency-update
