Repository scala-steward-org/scala-steward, pull requests merged in 2020-10, with the labels that each got.

#1634 Update coursier, coursier-cats-interop to 2.0.0
  project/Dependencies.scala
Labels: dependency-update

#1635 Clean up and remove duplication in VCSApiAlg
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlgTest.scala
Labels: refactoring

#1636 Add application name and version to the help message
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
Labels: enhancement

#1638 Do not require Sync for NurtureAlg
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: refactoring

#1640 Avoid duplicated VCSApiAlg.createForkOrGetRepo call
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
Labels: refactoring

#1641 Fix (modify/delete) conflicts in GitAlg.mergeTheirs
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
Labels: bug

#1642 Use Git's default commit message when resolving merge conflicts
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
Labels: enhancement

#1643 Update scalafmt-core to 2.7.4
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/RepositoryResponse.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
Labels: dependency-update

#1644 Use common val for gpg-sign option in GitAlg
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
Labels: refactoring

#1645 Remove some noise in GitAlg
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
Labels: refactoring

#1647 Update sbt-tpolecat to 0.1.14
  project/plugins.sbt
Labels: dependency-update

#1648 Update coursier, coursier-cats-interop to 2.0.1
  project/Dependencies.scala
Labels: dependency-update

#1649 Use immutable references for the Cats 2.2.0 Scalafix migration
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#1652 Update coursier, coursier-cats-interop to 2.0.2
  project/Dependencies.scala
Labels: dependency-update

#1650 Load Scalafix migrations from this repository
  docs/scalafix-migrations.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationsLoader.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/ScalafixMigrations.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationsLoaderTest.scala
Labels: enhancement

#1653 Use File in Cli.Args
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
Labels: refactoring

#1654 Pass extra env vars to all exec calls
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: enhancement

#1656 Update sbt-native-packager to 1.7.6
  project/plugins.sbt
Labels: dependency-update

#1655 Group process and sandbox related configuration
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationsLoader.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationsLoaderTest.scala
Labels: refactoring

#1657 Remove unused Config.cacheMissDelay
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: refactoring

#1658 Rename *Throwable aliases to *Throw
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationsLoader.scala
  modules/core/src/main/scala/org/scalasteward/core/update/GroupMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/RepoOut.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: refactoring

#1660 Test MillAlg.getDependencies
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
Labels: testing

#1659 Run mill with execSandboxed
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  scripts/run.sh
Labels: enhancement

#1661 Update coursier, coursier-cats-interop to 2.0.3
  project/Dependencies.scala
Labels: dependency-update

#1663 Add fs2-io as dependency explicitly
  build.sbt
  project/Dependencies.scala
Labels: build

#1662 Replace @daily, @weekly, @monthly with arbitrary timespans
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestFrequency.scala
  modules/core/src/main/scala/org/scalasteward/core/util/dateTime.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestFrequencyTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestsConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
Labels: enhancement

#1664 DRY loading and merging the default repo config
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
Labels: refactoring

#1665 Do not ignore includeScala from the default RepoConfig
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
Labels: bug

#1666 Inline expression in UpdateAlg.findUpdate
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
Labels: refactoring

#1668 Update http4s-async-http-client, ... to 0.21.8
  project/Dependencies.scala
Labels: dependency-update

#1669 Update scalafmt-core to 2.7.5
  .scalafmt.conf
Labels: dependency-update

#1667 Close obsolete pull requests in the NurtureAlg
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/github/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
Labels: enhancement

#1671 Update sbt-explicit-dependencies to 0.2.14
  project/plugins.sbt
Labels: dependency-update

#1639 Update sbt to 1.4.0
  project/build.properties
Labels: dependency-update

#1672 Close obsolete PRs only if a PR was created or updated
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: enhancement

#1673 Run scalafmt when upgrading scalafmt (opt-out)
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/ScalafmtConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
Labels: enhancement

#1675 Test FilterAlg.localFilter instead of FilterAlg.globalFilter
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: testing

#1676 Run scalafmt with --non-interactive
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
Labels: enhancement

#1678 Check that git and scalafmt can be executed in SelfCheckAlg
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
Labels: enhancement

#1679 Do not check in StewardPlugin if dependencies are defined in build files
  modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala
Labels: enhancement

#1680 Update sbt to 1.4.1
  project/build.properties
Labels: dependency-update

#1681 Install scalafmt on Dockerfile
  build.sbt
Labels: build

#1682 Change scalafmt commit message and add version
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: enhancement

#1684 Recognize NIGHTLY as pre-release identifier
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1685 Update sbt-explicit-dependencies to 0.2.15
  project/plugins.sbt
Labels: dependency-update

#1687 Update coursier, coursier-cats-interop to 2.0.4
  project/Dependencies.scala
Labels: dependency-update

#1688 Recognize hashes with "g" prefix in versions
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: bug

#1689 Update coursier, coursier-cats-interop to 2.0.5
  project/Dependencies.scala
Labels: dependency-update

#1690 Generalize FileAlg.findFiles
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
Labels: refactoring

#1691 Update sbt-wartremover, wartremover to 2.4.11
  project/plugins.sbt
Labels: dependency-update

#1686 Add ability to search for updates with different artifact id and / or group id
  .gitignore
  README.md
  docs/artifact-migrations.md
  docs/faq.md
  docs/running.md
  docs/scalafix-migrations.md
  modules/core/src/main/resources/artifact-migrations.conf
  modules/core/src/main/resources/group-migrations.conf
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/ArtifactMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/update/ArtifactMigrationsTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/GroupMigrationsTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#1692 Update sbt-wartremover, wartremover to 2.4.12
  project/plugins.sbt
Labels: dependency-update

#1694 Use approximate equality for parseFiniteDuration test
  modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
Labels: testing

#1696 Differentiate between non-set and empty file extensions
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
Labels: refactoring

#1697 Clean up some RepoConfig classes
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/CommitsConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestFrequency.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateStrategy.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/ScalafmtConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: refactoring

#1701 Replace http4s-async-http-client with http4s-okhttp-client
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  project/Dependencies.scala
Labels: bug

#1702 Pass environment variables as List to process.slurp
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
Labels: refactoring

#1704 Update scalacheck to 1.15.0
  project/Dependencies.scala
Labels: dependency-update

#1703 Allow passing environment variables to execSandboxed
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: enhancement
