Repository scala-steward-org/scala-steward, pull requests merged in 2020-09, with the labels that each got.

#1588 Add preliminary Scalafix migration for Cats 2.2.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#1593 Update sbt-scalafix to 0.9.20
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1594 Update Scalafix migration for Cats 2.2.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#1595 Sort Scalafix migrations and use more immutable references
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#1596 Update newVersion of Scalafix migration for Cats 2.2.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#1597 Update mill-scalalib to 0.8.0-8-0a8d46
  project/Dependencies.scala
Labels: dependency-update

#1601 Update Scala to 2.13.3
  .travis.yml
  build.sbt
Labels: dependency-update

#1602 Update cats-core, cats-laws to 2.2.0
  project/Dependencies.scala
Labels: dependency-update

#1604 Ignore "scala" as search term in the "relaxed" heuristic
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: bug

#1607 Update cats-effect to 2.2.0
  project/Dependencies.scala
Labels: dependency-update

#1609 Update scalafmt-core to 2.7.0
  .scalafmt.conf
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Scope.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/JsonCodecTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
Labels: dependency-update

#1610 Update mill-scalalib to 0.8.0-10-096f6f
  project/Dependencies.scala
Labels: dependency-update

#1611 Update mill-scalalib to 0.8.0-11-8cd135
  project/Dependencies.scala
Labels: dependency-update

#1612 Update commons-io to 2.8.0
  project/Dependencies.scala
Labels: dependency-update

#1614 Update coursier, coursier-cats-interop to 2.0.0-RC6-26
  project/Dependencies.scala
Labels: dependency-update

#1616 Update scalafmt-core to 2.7.1
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
Labels: dependency-update

#1618 Delete file in createTemporarily if writeFile fails
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
Labels: bug

#1619 Tweak and test splitDuration
  modules/core/src/main/scala/org/scalasteward/core/util/dateTime.scala
  modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
Labels: testing

#1620 Update scalafmt-core to 2.7.2
  .scalafmt.conf
Labels: dependency-update

#1621 Update refined, refined-cats, ... to 0.9.16
  project/Dependencies.scala
Labels: dependency-update

#1617 Fix transitivity of Order[Version]
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: bug

#1622 Improve Arbitrary[Version]
  build.sbt
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: testing

#1623 Update sbt-scalafix to 0.9.21
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1626 Update refined, refined-cats, ... to 0.9.17
  project/Dependencies.scala
Labels: dependency-update

#1627 Support `--help` and `--usage` CLI options
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
Labels: enhancement

#1629 Do not print stack trace if Cli.parseArgs fails
  modules/core/src/main/scala/org/scalasteward/core/Main.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
Labels: enhancement

#1630 Update scalafmt-core to 2.7.3
  .scalafmt.conf
Labels: dependency-update
