Repository scala-steward-org/scala-steward, pull requests merged in 2020-02, with the labels that each got.

#1254 should "allow" behave like white list?
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: enhancement

#1276 Improve the wording of the documentation
  docs/faq.md
  docs/repo-specific-configuration.md
Labels: documentation

#1277 Check artifacts that are not in a repository less frequently
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
Labels: enhancement

#1280 Update case-app to 2.0.0-M11
  project/Dependencies.scala
Labels: dependency-update

#1278 Update coursier, coursier-cats-interop to 2.0.0-RC6
  build.sbt
  project/Dependencies.scala
Labels: dependency-update

#1279 Update coursier, coursier-cats-interop to 2.0.0-RC6-1
  project/Dependencies.scala
Labels: dependency-update

#1281 Update http4s-async-http-client, ... to 0.21.0-RC3
  project/Dependencies.scala
Labels: dependency-update

#1282 Update sbt to 1.3.8
  project/build.properties
Labels: dependency-update

#1287 Update credit section in README
  README.md
Labels: administration

#1288 Update http4s-async-http-client, ... to 0.21.0-RC4
  project/Dependencies.scala
Labels: dependency-update

#1290 Log parsing or decoding errors in JsonKeyValueStore
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
Labels: enhancement

#1292 Update case-app to 2.0.0-M12
  project/Dependencies.scala
Labels: dependency-update

#1294 Update case-app to 2.0.0-M13
  project/Dependencies.scala
Labels: dependency-update

#1295 Document the Scope data type
  modules/core/src/main/scala/org/scalasteward/core/data/Scope.scala
Labels: documentation

#1296 Allow editing all .yml files and not only .travis.yml
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
Labels: enhancement

#1274 Support version suffixes in `UpdatePattern`
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: enhancement

#1299 Update cats-effect to 2.1.1
  project/Dependencies.scala
Labels: dependency-update

#1300 Update circe-generic, circe-literal, ... to 0.13.0
  project/Dependencies.scala
Labels: dependency-update

#1301 Update sbt-ci-release to 1.5.2
  project/plugins.sbt
Labels: dependency-update

#1302 Update coursier, coursier-cats-interop to 2.0.0-RC6-2
  project/Dependencies.scala
Labels: dependency-update

#1303 Update http4s-async-http-client, ... to 0.21.0-RC5
  project/Dependencies.scala
Labels: dependency-update

#1306 Update http4s-async-http-client, ... to 0.21.0
  project/Dependencies.scala
Labels: dependency-update

#1305 Update coursier, coursier-cats-interop to 2.0.0-RC6-3
  project/Dependencies.scala
Labels: dependency-update

#1307 Update coursier, coursier-cats-interop to 2.0.0-RC6-4
  project/Dependencies.scala
Labels: dependency-update

#1308 Include all release related links in PR body
  modules/core/src/main/scala/org/scalasteward/core/data/ReleaseRelatedUrl.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#1310 Update sbt-scalajs-crossproject to 1.0.0
  project/plugins.sbt
Labels: dependency-update

#1312 Update circe-generic-extras to 0.13.0
  project/Dependencies.scala
Labels: dependency-update

#1313 Add FileAlg.readResource
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: refactoring

#1309 Load Scalafix migrations once at start-up
  docs/scalafix-migrations.md
  modules/core/src/main/resources/scalafix-migrations.conf
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/Migration.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/ScalafixMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
Labels: enhancement

#1317 Update coursier, coursier-cats-interop to 2.0.0-RC6-5
  project/Dependencies.scala
Labels: dependency-update

#1320 Update coursier, coursier-cats-interop to 2.0.0-RC6-6
  project/Dependencies.scala
Labels: dependency-update

#1318 Fix invalid sbt syntax
  docs/running.md
Labels: documentation

#1322 Update coursier, coursier-cats-interop to 2.0.0-RC6-7
  project/Dependencies.scala
Labels: dependency-update

#1323 Don't use Uri.unsafeFromString in PullRequestRepository
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/uri.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
Labels: refactoring

#1324 Update http4s-async-http-client, ... to 0.21.1
  project/Dependencies.scala
Labels: dependency-update

#1325 Remove duplicated versions in VersionsCache
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
Labels: enhancement

#1328 Add links to PRs where Scalafix migrations were applied
  docs/scalafix-migrations.md
Labels: documentation

#1329 Update scalafmt-core to 2.4.1
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
  project/Dependencies.scala
Labels: dependency-update

#1331 Update coursier, coursier-cats-interop to 2.0.0-RC6-8
  project/Dependencies.scala
Labels: dependency-update

#1332 Update coursier, coursier-cats-interop to 2.0.0-RC6-9
  project/Dependencies.scala
Labels: dependency-update

#1335 Use Timestamp in VersionsCache and RefreshErrorAlg
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/Timestamp.scala
Labels: refactoring

#1337 Update sbt-wartremover, wartremover to 2.4.4
  project/plugins.sbt
Labels: dependency-update

#1338 Update coursier, coursier-cats-interop to 2.0.0-RC6-10
  project/Dependencies.scala
Labels: dependency-update

#1339 Make frequency an optional field
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: refactoring

#1342 Update scalatest to 3.1.1
  project/Dependencies.scala
Labels: dependency-update

#1343 Update discipline-scalatest to 1.0.1
  project/Dependencies.scala
Labels: dependency-update

#1344 Make commites.message optional
  modules/core/src/main/scala/org/scalasteward/core/git/package.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/CommitsConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/git/gitTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: refactoring

#1346 Update scalafmt-core to 2.4.2
  .scalafmt.conf
Labels: dependency-update

#1347 Update sbt-tpolecat to 0.1.11
  project/plugins.sbt
Labels: dependency-update

#1349 Update monocle-core to 2.0.2
  project/Dependencies.scala
Labels: dependency-update

#1350 Update sbt-wartremover, wartremover to 2.4.5
  project/plugins.sbt
Labels: dependency-update

#1351 Update cats-kernel-laws to 2.1.1
  project/Dependencies.scala
Labels: dependency-update
