Repository scala-steward-org/scala-steward, pull requests merged in 2020-01, with the labels that each got.

#1207 Use baseDirectory in runSteward sbt task
  build.sbt
Labels: build

#1210 Use Coursier to double-check our version ordering
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1211 Fix duplicated artifactIds in PR body
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
Labels: bug

#1212 Cleanup plugin installation automatically
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: enhancement

#1213 Use more precise types in UpdateState
  modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
Labels: refactoring

#1214 Require a scheme in SCM URL to prevent the generation of relative URLs
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
Labels: bug

#1215 Revert "Parallelize UpdateAlg.findUpdate"
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: refactoring

#1216 Revert "Revert "Parallelize UpdateAlg.findUpdate""
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: refactoring

#1217 Sort alpha components before non-zero numeric ones
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1218 Throttle (concurrent) requests to Maven Central
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/RateLimiter.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: enhancement

#1219 Update coursier, coursier-cats-interop to 2.0.0-RC5-5
  project/Dependencies.scala
Labels: dependency-update

#1220 Add our own versions cache
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/KeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/VersionsCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/RateLimiter.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: enhancement

#1221 Return cached versions if Coursier raises an error
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/VersionsCacheAlg.scala
Labels: enhancement

#1223 Refactor VersionsCacheAlg.getVersions
  modules/core/src/main/scala/org/scalasteward/core/update/VersionsCacheAlg.scala
Labels: refactoring

#1224 Log if a repo is skipped in RepoCacheAlg
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
Labels: enhancement

#1225 Use the same directory layout as Coursier for the versions cache
  modules/core/src/main/scala/org/scalasteward/core/update/VersionsCacheAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: refactoring

#1228 Update coursier, coursier-cats-interop to 2.0.0-RC5-6
  project/Dependencies.scala
Labels: dependency-update

#1229 Update sbt-header to 5.4.0
  project/plugins.sbt
Labels: dependency-update

#1227 Change updatePullRequests config to be an enum(always, on-conflicts, never)
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateStrategy.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: enhancement

#1232 Do not use MockState when testing parseRepoConfig
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: testing

#1206 Add migration rule for unreleased derevo 0.11.0
  modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
Labels: scalafix-migration

#1233 Update discipline-scalatest to 1.0.0-RC2
  project/Dependencies.scala
Labels: dependency-update

#1234 Update monocle-core to 2.0.1
  project/Dependencies.scala
Labels: dependency-update

#1235 Search in the parent pom for an artifact uri, if the actual pom contains none
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
Labels: enhancement

#1236 Don't use default resolvers for getting versions
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCache.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/VersionsCacheAlg.scala
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: enhancement

#1238 Don't use default resolvers for finding artifact URL
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
Labels: enhancement

#1230 Add new scio 0.8.0 scalafix rule
  modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
Labels: scalafix-migration

#1240 Try to make CoursierAlg.getArtifactUrlImpl clearer
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
Labels: refactoring

#1241 Do not store versions in VersionsCacheAlg
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCacheFacade.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/VersionsCacheAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: enhancement

#1242 Use resolver in SbtAlg.findAdditionalUpdates
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
Labels: bug

#1243 Update sbt to 1.3.7
  project/build.properties
Labels: dependency-update

#1244 Update sbt-explicit-dependencies to 0.2.12
  project/plugins.sbt
Labels: dependency-update

#1249 Update fs2-core to 2.2.1
  project/Dependencies.scala
Labels: dependency-update

#1252 Update sbt-native-packager to 1.6.0
  project/plugins.sbt
Labels: dependency-update

#1253 Run sbt in offline mode when querying dependencies
  modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala
  modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Labels: enhancement

#1255 Update http4s-async-http-client, ... to 0.21.0-RC1
  project/Dependencies.scala
Labels: dependency-update

#1256 Update discipline-scalatest to 1.0.0
  project/Dependencies.scala
Labels: dependency-update

#1257 Update case-app to 2.0.0-M10
  project/Dependencies.scala
Labels: dependency-update

#1258 Update sbt-doctest to 0.9.6
  project/plugins.sbt
Labels: dependency-update

#1259 Explicitly set Coursier's cache policies
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
Labels: enhancement

#1261 Update refined, refined-cats, ... to 0.9.12
  project/Dependencies.scala
Labels: dependency-update

#1264 Update http4s-async-http-client, ... to 0.21.0-RC2
  project/Dependencies.scala
Labels: dependency-update

#1265 Cache versions again
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Resolver.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  scripts/run.sh
Labels: enhancement

#1266 Ignore more local maven repositories
  modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Labels: enhancement

#1267 Get versions from resolvers in parallel
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
Labels: refactoring

#1268 Update sbt-scalafmt to 2.3.1
  project/plugins.sbt
Labels: dependency-update

#1269 Update fs2-core to 2.2.2
  project/Dependencies.scala
Labels: dependency-update

#1270 Update sbt-native-packager to 1.6.1
  project/plugins.sbt
Labels: dependency-update

#1271 Update cats-effect to 2.1.0
  project/Dependencies.scala
Labels: dependency-update

#1272 Run public instance for GitLab repositories
  scripts/run.sh
Labels: administration

#1273 Add Git repo manager as prefix to key value stores
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
Labels: enhancement
