Repository scala-steward-org/scala-steward, pull requests merged in 2020-08, with the labels that each got.

#1558 Update sbt-scalafmt to 2.4.2
  project/plugins.sbt
Labels: dependency-update

#1559 Include Babylon Health in community list
  README.md
Labels: administration

#1562 Add scalafix rules for upcoming 10.2.0 release
  modules/core/src/main/resources/scalafix-migrations.conf
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
Labels: scalafix-migration

#1564 Update mill-scalalib to 0.8.0-2-5e164d
  project/Dependencies.scala
Labels: dependency-update

#1565 Update scalatest to 3.2.1
  project/Dependencies.scala
Labels: dependency-update

#1567 Update sbt-buildinfo to 0.10.0
  project/plugins.sbt
Labels: dependency-update

#1568 Update sbt-doctest to 0.9.7
  project/plugins.sbt
Labels: dependency-update

#1566 Update http4s-async-http-client, ... to 0.21.7
  project/Dependencies.scala
Labels: dependency-update

#1570 Update case-app to 2.0.4
  project/Dependencies.scala
Labels: dependency-update

#1571 Update monocle-core to 2.1.0
  project/Dependencies.scala
Labels: dependency-update

#1572 Update sbt-native-packager to 1.7.5
  project/plugins.sbt
Labels: dependency-update

#1578 Update cron4s-core to 0.6.1
  project/Dependencies.scala
Labels: dependency-update

#1580 Update mill-scalalib to 0.8.0-5-1a410f
  project/Dependencies.scala
Labels: dependency-update

#1583 Update mill-scalalib to 0.8.0-6-bbbf19
  project/Dependencies.scala
Labels: dependency-update
