Repository scala-steward-org/scala-steward, pull requests merged in 2020-07, with the labels that each got.

#1515 Make FileAlg.createTemporarily a derived operation
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
Labels: refactoring

#1517 Do not repeatedly compute coursier.util.Monad
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
Labels: refactoring

#1508 Update sbt to 1.3.13
  project/build.properties
Labels: dependency-update

#1519 Do not restrict Scalafmt updates to sbt
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Scope.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
Labels: enhancement

#1520 Update mill-scalalib to 0.7.4
  build.sbt
Labels: dependency-update

#1521 Prepare for update to Scala 2.13.3
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
Labels: refactoring

#1522 Update sbt-scalafix to 0.9.18
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1501 Make plugin work for 0.6 and Scala 2.12 as well
  .travis.yml
  build.sbt
  modules/mill-plugin/src/main/scala-2.12/org/scalasteward/mill/plugin/package.scala
  modules/mill-plugin/src/main/scala/org/scalasteward/mill/plugin/StewardPlugin.scala
  project/plugins.sbt
Labels: enhancement

#1524 Update mill-scalalib to 0.6.3
  build.sbt
Labels: dependency-update

#1525 Update scalafmt-core to 2.6.2
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/Details.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: dependency-update

#1526 javac, curl and mill
  build.sbt
  project/Dependencies.scala
Labels: build

#1527 Do not use mill scripts in repositories
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
Labels: enhancement

#1528 Find keywords that contain additional punctuation
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
Labels: enhancement

#1529 Update coursier, coursier-cats-interop to 2.0.0-RC6-22
  project/Dependencies.scala
Labels: dependency-update

#1530 Update sbt-native-packager to 1.7.4
  project/plugins.sbt
Labels: dependency-update

#1531 Update coursier, coursier-cats-interop to 2.0.0-RC6-23
  project/Dependencies.scala
Labels: dependency-update

#1537 Update scalafmt-core to 2.6.3
  .scalafmt.conf
Labels: dependency-update

#1539 Update cats-effect to 2.1.4
  project/Dependencies.scala
Labels: dependency-update

#1540 Update sbt-wartremover to 2.4.10
  project/plugins.sbt
Labels: dependency-update

#1542 Update sbt-scalafix to 0.9.19
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1545 Update refined, refined-cats, ... to 0.9.15
  project/Dependencies.scala
Labels: dependency-update

#1546 Update scalafmt-core to 2.6.4
  .scalafmt.conf
Labels: dependency-update

#1547 Update mill-scalalib to 0.8.0
  project/Dependencies.scala
Labels: dependency-update

#1548 Update discipline-scalatest to 2.0.0
  project/Dependencies.scala
Labels: dependency-update

#1549 Treat versions with hashes as pre-releases
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: bug

#1551 Update mill-scalalib to 0.8.0-1-d81662
  project/Dependencies.scala
Labels: dependency-update

#1552 Fix Version.preReleaseIndex
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: bug

#1553 Prevent updates to less stable pre-release versions
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: bug

#1554 Store indices in Version.Component
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
Labels: refactoring

#1556 Update coursier, coursier-cats-interop to 2.0.0-RC6-24
  project/Dependencies.scala
Labels: dependency-update
