Repository scala-steward-org/scala-steward, pull requests merged in 2020-12, with the labels that each got.

#1778 Update sbt-explicit-dependencies to 0.2.16
  project/plugins.sbt
Labels: dependency-update

#1779 Ignore errors while cloning Git submodules
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: enhancement

#1780 Update refined, refined-cats, ... to 0.9.19
  project/Dependencies.scala
Labels: dependency-update

#1781 Update kind-projector to 0.11.2
  project/Dependencies.scala
Labels: dependency-update

#1785 Update sbt-tpolecat to 0.1.16
  project/plugins.sbt
Labels: dependency-update

#1786 Update sbt-ci-release to 1.5.5
  project/plugins.sbt
Labels: dependency-update

#1787 Remove olafurpg/setup-gpg
  .github/workflows/ci.yml
  build.sbt
Labels: build

#1789 Add sbt-http4s-org to knownGitHubActions
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
Labels: enhancement

#1791 Prevent updates if versions differ only in their hashes
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1792 Prevent updates from versions w/o hash to versions with hash
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1794 Do not recognize dates as hashes in versions
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1796 Ignore errors when executing post-update hooks
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
Labels: enhancement

#1797 Do not sort updates by Scalafix migrations
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: enhancement

#1798 Version: ignore pre-release identifier after a hash
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#1799 Add more test cases for Version.selectNext
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: testing

#1800 Use a separate commit for Scalafix changes
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
Labels: enhancement

#1803 Update http4s-circe, http4s-client, ... to 0.21.14
  project/Dependencies.scala
Labels: dependency-update

#1805 Remove remnants of http4s-async-http-client from the build
  build.sbt
Labels: build

#1804 Add hashes to Arbitrary[Version] instance
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: testing

#1802 Simplify version parsing
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
Labels: refactoring

#1806 Add Scalafix documentation URL to commit body
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
Labels: enhancement

#1808 Update sbt to 1.4.5
  project/build.properties
Labels: dependency-update

#1809 Run Scalafix migrations only if version can be bumped
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
Labels: enhancement

#1810 Pass RepoCache from RepoCacheAlg to PruningAlg
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: refactoring

#1812 Update scalacheck to 1.15.2
  project/Dependencies.scala
Labels: dependency-update

#1811 Allow arbitrary punctuation before scala-steward:off
  modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: enhancement

#1813 Update sbt-native-packager to 1.8.0
  project/plugins.sbt
Labels: dependency-update

#1815 Update cats-core, cats-laws to 2.3.1
  project/Dependencies.scala
Labels: dependency-update

#1816 Update cats-effect to 2.3.1
  project/Dependencies.scala
Labels: dependency-update

#1817 Use *Throw aliases from Cats and Cats Effect
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationsLoader.scala
  modules/core/src/main/scala/org/scalasteward/core/update/ArtifactMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/RepoOut.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: refactoring

#1821 Update munit, munit-scalacheck to 0.7.20
  project/Dependencies.scala
Labels: dependency-update

#1822 Update discipline-munit to 1.0.4
  project/Dependencies.scala
Labels: dependency-update

#1823 Init Git submodules after syncing with upstream repo
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: bug

#1824 Move dotdot function to FileGitAlg companion
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/package.scala
Labels: refactoring

#1825 Update mill-scalalib to 0.9.4
  project/Dependencies.scala
Labels: dependency-update

#1826 More accurately log when we're cloning and syncing
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: refactoring

#1827 Update fs2-core, fs2-io to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#1829 Add Max Buffer Size to Config
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
Labels: enhancement

#1830 Add KeyValueStore.getOrElse
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/KeyValueStore.scala
Labels: refactoring

#1828 Allow updates.limit option to be zero
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
Labels: enhancement

#1832 Update bcprov-jdk15to18 to 1.68
  project/Dependencies.scala
Labels: dependency-update

#1833 add scalafix for cats-parse 0.3.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#1834 Change findPullRequest to findLatestPullRequests
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
Labels: bug

#1836 Update coursier, coursier-cats-interop to 2.0.8
  project/Dependencies.scala
Labels: dependency-update

#1837 Update sbt to 1.4.6
  project/build.properties
Labels: dependency-update

#1838 Implement KVStore.{put, modifyF} in terms of set
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/KeyValueStore.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
Labels: refactoring

#1839 Do not unnecessarily write to KVStore in RefreshErrorAlg
  modules/core/src/main/scala/org/scalasteward/core/persistence/KeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
Labels: refactoring

#1842 Add caching layer to pull requests store
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/CachingKeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/Repo.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
Labels: enhancement

#1844 Don't remove the local branch. It doesn't exist anymore
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
Labels: bug

#1845 Show the old version in oldVersionNote
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: bug

#1846 Remove branch if PR is closed by project maintainer
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: enhancement

#1847 Show all details in the PR body below each other
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: refactoring

#1848 Sort obsolete PRs by their number
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
Labels: refactoring

#1849 Use log level WARN for expected and ignored errors
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
Labels: refactoring

#1850 Add minimal CLI help
  docs/help.md
  docs/running.md
Labels: documentation

#1851 Ignore error if removing remote branch fails
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
Labels: bug

#1852 Show duration a repo is skipped in RefreshErrorAlg
  modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
Labels: enhancement

#1854 git fetch with --force
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: bug
