Repository scala-steward-org/scala-steward, pull requests merged in 2021-01, with the labels that each got.

#1856 Update http4s-circe, http4s-client, ... to 0.21.15
  project/Dependencies.scala
Labels: dependency-update

#1858 Simplify extractRepoVCSType
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
Labels: refactoring

#1860 Use safe Decoder[Uri] in BitbucketServer JSON layer
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
Labels: refactoring

#1861 Use common naming convention for bitbucketserver.JSON
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
Labels: refactoring

#1862 Clean up BitbucketServerApiAlg
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Url.scala
Labels: refactoring

#1863 Fix BitbucketServerApiAlg.closePullRequest
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Url.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
Labels: bug

#1857 Check Monoid laws for all repoconfig classes
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/CommitsConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/ScalafmtConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/CommitsConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestsConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/ScalafmtConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
Labels: enhancement

#1864 Rename HttpExistenceClient to UrlChecker
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
Labels: refactoring

#1866 BitbucketServer: do not hardcode default branch
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Url.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
Labels: enhancement

#1867 Update refined, refined-cats, ... to 0.9.20
  project/Dependencies.scala
Labels: dependency-update

#1869 Update atto-core to 0.9.0
  project/Dependencies.scala
Labels: dependency-update

#1868 Add Git, GitLab, and BitbucketServer config classes
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Labels: refactoring

#1874 Do not read RepoCache and RepoConfig twice
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/RepoData.scala
  modules/core/src/main/scala/org/scalasteward/core/data/UpdateData.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Labels: refactoring

#1878 Create commit for Scalafix migration even if it failed
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
Labels: bug

#1881 Update sbt-scalafix to 0.9.25
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1882 Make RepoConfig.buildRoots optional
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/BuildRootConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: refactoring

#1884 Update kind-projector to 0.11.3
  project/Dependencies.scala
Labels: dependency-update

#1883 BuildToolAlg.runMigrations -> runMigration
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
Labels: refactoring

#1885 Remove Sync from Config.vcsUser
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
Labels: refactoring

#1888 Reuse Context in tests
  modules/core/src/main/scala/org/scalasteward/core/Main.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationsLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/ArtifactMigrationsTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: refactoring

#1891 Test that runF returns ExitCode.Success
  modules/core/src/test/scala/org/scalasteward/core/application/StewardAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: testing

#1887 Update sbt-github-actions to 0.10.0
  build.sbt
  project/plugins.sbt
Labels: dependency-update

#1892 Update sbt-github-actions to 0.10.1
  project/plugins.sbt
Labels: dependency-update

#1893 Update coursier, coursier-cats-interop to 2.0.9
  project/Dependencies.scala
Labels: dependency-update

#1894 More precise Scalafix commit msg
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
Labels: enhancement

#1895 Update sbt-doctest to 0.9.9
  project/plugins.sbt
Labels: dependency-update

#1897 improve error message in case git or scalafmt is not on the path
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
Labels: enhancement

#1898 Use MUnit also for the doctests
  build.sbt
Labels: testing

#1896 Test FileAlg.isRegularFile
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
Labels: testing

#1900 Update munit, munit-scalacheck to 0.7.21
  project/Dependencies.scala
Labels: dependency-update

#1901 Update http4s-circe, http4s-client, ... to 0.21.16
  project/Dependencies.scala
Labels: dependency-update

#1902 Use Blocker for Process#waitFor in slurp
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
Labels: refactoring

#1904 Add scalafix migrations for fd4s/fs2-kafka
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#1905 Update mill-scalalib to 0.9.5
  project/Dependencies.scala
Labels: dependency-update

#1909 fix closing a pull request in bitbucket cloud
  README.md
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/Url.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
Labels: bug

#1910 Update discipline-munit to 1.0.5
  project/Dependencies.scala
Labels: dependency-update

#1911 Update sbt to 1.4.7
  project/build.properties
Labels: dependency-update
