Repository scala-steward-org/scala-steward, pull requests merged in 2021-07, with the labels that each got.

#2172 Update fs2-core, fs2-io to 3.0.5
  project/Dependencies.scala
Labels: dependency-update

#2173 Update munit, munit-scalacheck to 0.7.27
  project/Dependencies.scala
Labels: dependency-update

#2174 Update sbt-scalajs-crossproject to 1.1.0
  project/plugins.sbt
Labels: dependency-update

#2175 Update fs2-core, fs2-io to 3.0.6
  project/Dependencies.scala
Labels: dependency-update

#2177 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#2179 Add sbt-davenverse to the plugins that depend on sbt-github-actions
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
Labels: enhancement

#2180 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#2181 Rename Monocle organization
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2182 Update commons-io to 2.11.0
  project/Dependencies.scala
Labels: dependency-update

#2185 Update mill-scalalib to 0.9.9
  project/Dependencies.scala
Labels: dependency-update

#2186 Update logback-classic to 1.2.4
  project/Dependencies.scala
Labels: dependency-update

#2188 Update cats-effect to 3.2.0
  project/Dependencies.scala
Labels: dependency-update

#2189 Update logback-classic to 1.2.5
  project/Dependencies.scala
Labels: dependency-update

#2190 Update cats-effect to 3.2.1
  project/Dependencies.scala
Labels: dependency-update
