Repository scala-steward-org/scala-steward, pull requests merged in 2021-02, with the labels that each got.

#1915 Do not wrap UrlChecker in Resource
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
Labels: refactoring

#1916 Rename SupportedVCS to VCSType
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSType.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
Labels: refactoring

#1918 BitbucketServer: list also declined and merged PRs
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Url.scala
Labels: bug

#1919 Update http4s-dsl to 0.21.17
  project/Dependencies.scala
Labels: dependency-update

#1920 Update atto-core to 0.9.1
  project/Dependencies.scala
Labels: dependency-update

#1921 Update http4s-circe, http4s-client, ... to 0.21.18
  project/Dependencies.scala
Labels: dependency-update

#1924 Add an example of running in a Bitbucket pipeline
  docs/running.md
Labels: documentation

#1925 Remove effect from JsonKeyValueStore#jsonFile
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
Labels: refactoring

#1926 Update cats-core, cats-laws to 2.4.0
  project/Dependencies.scala
Labels: dependency-update

#1927 Update cats-core, cats-laws to 2.4.1
  project/Dependencies.scala
Labels: dependency-update

#1930 Update coursier, coursier-cats-interop to 2.0.11
  project/Dependencies.scala
Labels: dependency-update

#1931 Update http4s-circe, http4s-client, ... to 0.21.19
  project/Dependencies.scala
Labels: dependency-update

#1932 Update initialVersion of sbt-pgp artifact migration
  modules/core/src/main/resources/artifact-migrations.conf
Labels: enhancement

#1933 Update coursier-cats-interop to 2.0.12
  project/Dependencies.scala
Labels: dependency-update

#1934 Extract correct PR URL from Bitbucket API response
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/json.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/JsonCodecTest.scala
Labels: bug

#1935 Update scalacheck to 1.15.3
  project/Dependencies.scala
Labels: dependency-update

#1936 Update munit, munit-scalacheck to 0.7.22
  project/Dependencies.scala
Labels: dependency-update

#1937 Update discipline-munit to 1.0.6
  project/Dependencies.scala
Labels: dependency-update

#1938 Update cats-core, cats-laws to 2.4.2
  project/Dependencies.scala
Labels: dependency-update

#1941 Update cats-effect to 2.3.3
  project/Dependencies.scala
Labels: dependency-update

#1942 Update fs2-core, fs2-io to 2.5.1
  project/Dependencies.scala
Labels: dependency-update

#1943 Update refined, refined-cats, ... to 0.9.21
  project/Dependencies.scala
Labels: dependency-update

#1944 Update fs2-core, fs2-io to 2.5.2
  project/Dependencies.scala
Labels: dependency-update

#1945 Escape punctuation in UpdateHeuristic.toFlexibleRegex
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: bug

#1946 Do not allow heuristics below 'moduleId' to modify ModuleIDs
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: bug

#1947 Verify that #960 has been fixed by #1946
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: testing

#1948 Ignore ancient commons-net versions
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1949 Update fs2-core, fs2-io to 2.5.3
  project/Dependencies.scala
Labels: dependency-update

#1950 Extract browsableUriFromString from getScmUrlOrHomePage
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/uri.scala
Labels: refactoring

#1954 Merge MockState#{commands, logs} to MockState#trace
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: refactoring, testing

#1955 Add another Cmd.apply
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: refactoring, testing

#1959 Update atto-core to 0.9.2
  project/Dependencies.scala
Labels: dependency-update

#1962 Use default FileAlg to implement MockFileAlg, take 2
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationsLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: testing

#1953 Extract function from runScalafixMigrations
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
Labels: refactoring

#1964 Use a common root directory for file operations in tests
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationsLoaderTest.scala
Labels: refactoring, testing

#1969 Update log4cats-slf4j to 1.2.0
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/WorkspaceAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationsLoader.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockLogger.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
  project/Dependencies.scala
Labels: dependency-update

#1967 Migrate log4cats artifacts
  modules/core/src/main/resources/artifact-migrations.conf
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: artifact-migration, scalafix-migration

#1961 Create draft PRs for scala update
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/IncludeScalaStrategy.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#1972 add more scalatestplus migration configs
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#1971 Update scala-library to 2.13.4
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheRepository.scala
Labels: dependency-update

#1975 Update sbt-scalafix to 0.9.26
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#1978 Test case for 1977
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
Labels: bug, testing

#1980 Move 'scalafix' package into 'edit' package and rename classes
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigration.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinder.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoader.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/WorkspaceAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubAuthAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockWorkspaceAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Labels: refactoring
