Repository scala-steward-org/scala-steward, pull requests merged in 2021-09, with the labels that each got.

#2213 Update monocle-core to 3.1.0
  project/Dependencies.scala
Labels: dependency-update

#2214 Update sbt-assembly to 1.1.0
  project/plugins.sbt
Labels: dependency-update

#2215 Update http4s-circe, http4s-client, ... to 1.0.0-M25
  project/Dependencies.scala
Labels: dependency-update

#2216 sbt-avro artifact migration
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2217 Update scalafmt-core to 3.0.2
  .scalafmt.conf
Labels: dependency-update

#2218 Update cats-effect to 3.2.6
  project/Dependencies.scala
Labels: dependency-update

#2219 Update cats-effect to 3.2.7
  project/Dependencies.scala
Labels: dependency-update

#2220 Update scalacache-caffeine to 1.0.0-M3
  project/Dependencies.scala
Labels: dependency-update

#2221 Update scalacache-caffeine to 1.0.0-M4
  project/Dependencies.scala
Labels: dependency-update

#2222 Update cats-effect to 3.2.8
  project/Dependencies.scala
Labels: dependency-update

#2223 Update logback-classic to 1.2.6
  project/Dependencies.scala
Labels: dependency-update

#2224 Update scalafmt-core to 3.0.3
  .scalafmt.conf
Labels: dependency-update

#2225 Update fs2-core, fs2-io to 3.1.2
  project/Dependencies.scala
Labels: dependency-update

#2226 Update scala-library to 2.12.15
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: dependency-update

#2228 Revert "Update scala-library to 2.12.15"
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: invalid

#2144 Update circe-generic, circe-literal, ... to 0.14.1
  project/Dependencies.scala
Labels: dependency-update

#2145 Update circe-generic-extras to 0.14.1
  project/Dependencies.scala
Labels: dependency-update

#2230 Migrate to newer artifact version
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2233 Update sbt-scoverage to 1.9.0
  project/plugins.sbt
Labels: dependency-update

#2234 Update sbt-scalafix to 0.9.31
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#2235 Update scalafmt-core to 3.0.4
  .scalafmt.conf
Labels: dependency-update

#2236 Update cats-effect to 3.2.9
  project/Dependencies.scala
Labels: dependency-update

#2237 Add artifact migration for better-tostring
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2135 Support reading and updating .mill-version file
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillVersionParserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
Labels: enhancement

#2239 Add val for the name of the scalafmt conf file
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
Labels: refactoring

#2240 Update http4s-circe, http4s-client, ... to 1.0.0-M27
  project/Dependencies.scala
Labels: dependency-update

#2243 Add artifact migration for sbt-ci-release
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2244 Update sbt-ci-release to 1.5.9
  project/plugins.sbt
Labels: dependency-update

#2242 Introduce EditAttempt enum
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAttempt.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
Labels: refactoring

#2249 Load artifact migrations from this repository
  docs/artifact-migrations.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/update/ArtifactMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactChange.scala
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactChanges.scala
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinder.scala
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsLoader.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/update/ArtifactMigrationsTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
Labels: enhancement

#2250 Use sbt slash syntax for publishing the docker image
  .github/workflows/ci.yml
  build.sbt
Labels: build

#2251 Update fs2-core, fs2-io to 3.1.3
  project/Dependencies.scala
Labels: dependency-update

#2253 Update scalafmt-core to 3.0.5
  .scalafmt.conf
Labels: dependency-update

#2255 Streamline attemptLog* functions
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
Labels: refactoring

#2254 Do not close old PRs that were manually updated
  modules/core/src/main/scala/org/scalasteward/core/git/Branch.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
Labels: enhancement

#2256 Rename logger.attempt*.bracket back to label
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
Labels: refactoring

#2257 Update munit-cats-effect-3 to 1.0.6
  project/Dependencies.scala
Labels: dependency-update
