Repository scala-steward-org/scala-steward, pull requests merged in 2021-11, with the labels that each got.

#2323 Set default `--refresh-backoff-period` to zero
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
Labels: enhancement

#2324 Test RefreshErrorAlg
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/repocache/RefreshErrorAlgTest.scala
Labels: testing

#2308 Support Scalafix migrations that target build files
  build.sbt
  modules/core/src/main/resources/scalafix-migrations.conf
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixCli.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigration.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
  repos.md
Labels: enhancement, scalafix-migration

#2329 Update sbt-scoverage to 1.9.2
  project/plugins.sbt
Labels: dependency-update

#2330 Set `User-Agent` header
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
Labels: enhancement

#2328 Allow running Scalafix migrations after version bump
  modules/core/src/main/resources/scalafix-migrations.conf
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigration.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinder.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSType.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/json.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestState.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoaderTest.scala
Labels: enhancement, scalafix-migration

#2311 codecov v2
  .github/workflows/ci.yml
  build.sbt
Labels: build

#2331 Set `http.agent` Java property
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
Labels: enhancement

#2333 Make methods in NurtureAlg private
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: refactoring

#2336 Update scalafmt-core to 3.1.0
  .scalafmt.conf
Labels: dependency-update

#2337 Support reading a default repo config from this repository
  build.sbt
  docs/help.md
  modules/core/src/main/resources/default.scala-steward.conf
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/data/package.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoader.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigLoader.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsLoader.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: enhancement

#2338 Generate "CLI help" doc from the code
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/docs/mdoc/help.md
Labels: documentation

#2339 Ignore the next Scala.js versions until they are announced.
  modules/core/src/main/resources/default.scala-steward.conf
Labels: administration

#2341 Update logback-classic to 1.2.7
  project/Dependencies.scala
Labels: dependency-update

#2342 Use whenA in some places
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Labels: refactoring

#2343 Derive UpdatePattern.Version decoder
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
Labels: refactoring

#2346 Update cats-parse to 0.3.5
  project/Dependencies.scala
Labels: dependency-update

#2345 Update sbt-scalafix to 0.9.32
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#2347 Update scalafmt-core to 3.1.1
  .scalafmt.conf
Labels: dependency-update

#2348 Add benchmark for UpdatesConfig.keep
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/UpdatesConfigBenchmark.scala
Labels: refactoring

#2349 Add Scastie about Version#selectNext to the FAQ
  docs/faq.md
  modules/docs/mdoc/faq.md
Labels: documentation

#2350 Update mill-scalalib to 0.9.10
  project/Dependencies.scala
Labels: dependency-update

#2351 Use Resource for temporarily creating and removing files
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/package.scala
Labels: refactoring

#2352 Update case-app to 2.1.0-M9
  project/Dependencies.scala
Labels: dependency-update

#2356 Improve formatting of UnexpectedResponse.getMessage
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/test/scala/org/scalasteward/core/util/UnexpectedResponseTest.scala
Labels: refactoring

#2358 Do not use traits for BuildToolAlg implementations
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
Labels: refactoring

#2354 Add migration of groupId for cats-time
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2360 Adjust docs for default repo config cli options
  docs/running.md
  modules/docs/mdoc/running.md
Labels: documentation

#2361 Update sbt-native-packager to 1.9.7
  project/plugins.sbt
Labels: dependency-update

#2362 Move UpdatePattern.Version to VersionPattern
  docs/repo-specific-configuration.md
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/UpdatesConfigBenchmark.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/VersionPattern.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: documentation, refactoring

#2364 Update sbt-scalafmt to 2.4.4
  project/plugins.sbt
Labels: dependency-update

#2366 Update cats-parse to 0.3.6
  project/Dependencies.scala
Labels: dependency-update

#2365 Add 'contains' matcher to VersionPattern
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/VersionPattern.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: enhancement

#2368 Extend selectNext test case
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: testing

#2369 Add case to selectNext test
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: testing

#2370 Update scalafmt-core to 3.1.2
  .scalafmt.conf
Labels: dependency-update

#2371 Delete update branch when syncing a fork
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/package.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: bug

#2367 Do not select versions with a "smaller" pre-release identifier
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: bug

#2372 Fix `git diff` call
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
Labels: bug

#2373 Fix `deleteRemoteBranch` call
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
Labels: bug

#2374 Save vertical space in UpdateHeuristicTest
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Labels: testing, refactoring

#2375 Reformat Scalafix migrations notes in PR
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#2378 Update sbt-scalafix to 0.9.33
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#2377 Rework syntax for creating updates in tests
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/showTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Labels: testing, refactoring

#2379 Update case-app to 2.1.0-M10
  project/Dependencies.scala
Labels: dependency-update

#2381 Update cats-core, cats-laws to 2.7.0
  project/Dependencies.scala
Labels: dependency-update

#2382 Update cats-effect to 3.3.0
  project/Dependencies.scala
Labels: dependency-update

#2380 Check `runAfterUpgrading` for formatting changed files
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
Labels: enhancement

#2384 Update scalafmt-core to 3.2.0
  .scalafmt.conf
Labels: dependency-update

#2385 Fix: `process.slurp` ignores the timeout
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
Labels: bug

#2386 Move `UpdateState` into its own file
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/UpdateState.scala
Labels: refactoring

#2387 Update refined, refined-scalacheck to 0.9.28
  project/Dependencies.scala
Labels: dependency-update
