Repository scala-steward-org/scala-steward, pull requests merged in 2021-05, with the labels that each got.

#2101 Update sbt-scoverage to 1.7.1
  project/plugins.sbt
Labels: dependency-update

#2102 Update sbt-scoverage to 1.7.2
  project/plugins.sbt
Labels: dependency-update

#2104 Update scalacheck to 1.15.4
  project/Dependencies.scala
Labels: dependency-update

#2105 Update atto-core to 0.9.4
  project/Dependencies.scala
Labels: dependency-update

#2106 Update sbt-scoverage to 1.7.3
  project/plugins.sbt
Labels: dependency-update

#2107 Update cats-parse to 0.3.3
  project/Dependencies.scala
Labels: dependency-update

#2109 Update sbt-scoverage to 1.8.0
  project/plugins.sbt
Labels: dependency-update

#2110 Update sbt-jmh to 0.4.1
  project/plugins.sbt
Labels: dependency-update

#2111 Update sbt-jmh to 0.4.2
  project/plugins.sbt
Labels: dependency-update

#2113 Update cats-core, cats-laws to 2.6.1
  project/Dependencies.scala
Labels: dependency-update

#2115 Update discipline-munit to 1.0.9
  project/Dependencies.scala
Labels: dependency-update

#2112 Update munit, munit-scalacheck to 0.7.26
  project/Dependencies.scala
Labels: dependency-update

#2114 Update cats-effect to 3.1.1
  project/Dependencies.scala
Labels: dependency-update

#2116 Update munit-cats-effect-3 to 1.0.3
  project/Dependencies.scala
Labels: dependency-update

#2118 Update fs2-core, fs2-io to 3.0.3
  project/Dependencies.scala
Labels: dependency-update

#2119 Update mill-scalalib to 0.9.7
  project/Dependencies.scala
Labels: dependency-update

#2120 Update cats-parse to 0.3.4
  project/Dependencies.scala
Labels: dependency-update

#2121 Update atto-core to 0.9.5
  project/Dependencies.scala
Labels: dependency-update

#2124 Update log4cats-slf4j to 2.1.1
  project/Dependencies.scala
Labels: dependency-update

#2125 Tweak 'specific' update heuristic
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
Labels: refactoring

#2128 Update sbt-scoverage to 1.8.1
  project/plugins.sbt
Labels: dependency-update

#2126 Add a migration rule for scalafix 0.9.28
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#2131 Update sbt-scalafix to 0.9.28
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#2132 Update fs2-core, fs2-io to 3.0.4
  project/Dependencies.scala
Labels: dependency-update

#2133 Update sbt-tpolecat to 0.1.18
  project/plugins.sbt
Labels: dependency-update

#2136 Update sbt-github-actions to 0.11.0
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependency-update

#2140 Update commons-io to 2.9.0
  project/Dependencies.scala
Labels: dependency-update

#2139 add alexarchambault libraries in artifact-migrations.conf
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2146 Update sbt-tpolecat to 0.1.19
  project/plugins.sbt
Labels: dependency-update

#2149 Update mill-scalalib to 0.9.8
  project/Dependencies.scala
Labels: dependency-update

#2150 Update scala-library to 2.12.14
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: dependency-update

#2147 Update http4s-circe, http4s-client, ... to 1.0.0-M23
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  project/Dependencies.scala
Labels: dependency-update

#2151 Update sbt-scoverage to 1.8.2
  project/plugins.sbt
Labels: dependency-update

#2155 Update sbt-scalafix to 0.9.29
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update
