Repository scala-steward-org/scala-steward, pull requests merged in 2021-04, with the labels that each got.

#2047 Update cats-parse to 0.3.2
  project/Dependencies.scala
Labels: dependency-update

#2048 Update log4cats-slf4j to 1.2.2
  project/Dependencies.scala
Labels: dependency-update

#2051 Update mill-scalalib to 0.9.6
  project/Dependencies.scala
Labels: dependency-update

#2054 Update refined, refined-scalacheck to 0.9.23
  project/Dependencies.scala
Labels: dependency-update

#2055 Run githubWorkflowGenerate on sbt updates
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
Labels: enhancement

#2056 Update sbt to 1.5.0
  .github/workflows/ci.yml
  project/build.properties
Labels: dependency-update

#2057 Change order of predicates for finding hooks
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
Labels: refactoring

#2049 Update log4cats-slf4j to 2.0.1
  project/Dependencies.scala
Labels: dependency-update

#2062 Update ScalaCache to 1.0.0-M2
  modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
  project/Dependencies.scala
Labels: dependency-update

#2063 Start using munit-cats-effect
  build.sbt
  modules/core/src/test/scala/org/scalasteward/core/application/StewardAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/package.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
  project/Dependencies.scala
Labels: refactoring, testing

#2064 Update munit-cats-effect-3 to 1.0.1
  project/Dependencies.scala
Labels: dependency-update

#2066 Remove unused kind-projector plugin
  build.sbt
  project/Dependencies.scala
Labels: build

#2067 Update circe-generic, circe-literal, ... to 0.14.0-M5
  project/Dependencies.scala
Labels: dependency-update

#2068 Add scalafix migration for fs2-kafka v1.5.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#2069 Remove wartremover in preparation for Scala 3
  build.sbt
  project/plugins.sbt
Labels: build

#2070 Remove better-monadic-for in preparation for Scala 3
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  project/Dependencies.scala
Labels: build, refactoring

#2071 `scala.io.Source` is blocking
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
Labels: refactoring

#2073 Bypass Git's pre-push hooks
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: enhancement

#2074 Bypass all Git hooks by setting hooksPath to /dev/null
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: enhancement

#2075 Organize imports
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/package.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestFrequencyTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/BranchOutTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/PullRequestOutTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/RepoOutTest.scala
Labels: refactoring

#2077 Update cats-effect to 3.0.2
  project/Dependencies.scala
Labels: dependency-update

#2079 Add Scalafix migration for http4s 0.22.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#2080 Update case-app to 2.0.5
  project/Dependencies.scala
Labels: dependency-update

#2083 Update case-app to 2.0.6
  project/Dependencies.scala
Labels: dependency-update

#2081 Remove updates.includeScala option
  docs/repo-specific-configuration.md
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/VersionBenchmark.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/IncludeScalaStrategy.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#2084 Fix some Scala 3 errors
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/git/Sha1.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateStrategy.scala
Labels: refactoring

#2085 Update munit, munit-scalacheck to 0.7.25
  project/Dependencies.scala
Labels: dependency-update

#2087 Update cats-core, cats-laws to 2.6.0
  project/Dependencies.scala
Labels: dependency-update

#2089 Update cats-effect to 3.1.0
  project/Dependencies.scala
Labels: dependency-update

#2090 Update refined, refined-scalacheck to 0.9.24
  project/Dependencies.scala
Labels: dependency-update

#2091 Update munit-cats-effect-3 to 1.0.2
  project/Dependencies.scala
Labels: dependency-update

#2092 Update fs2-core, fs2-io to 3.0.2
  project/Dependencies.scala
Labels: dependency-update

#2093 Update log4cats-slf4j to 2.1.0
  project/Dependencies.scala
Labels: dependency-update

#2095 Update sbt to 1.5.1
  project/build.properties
Labels: dependency-update

#2094 Update circe-generic, circe-literal, ... to 0.14.0-M6
  project/Dependencies.scala
Labels: dependency-update

#2100 Update sbt-scoverage to 1.7.0
  project/plugins.sbt
Labels: dependency-update
