Repository scala-steward-org/scala-steward, pull requests merged in 2021-03, with the labels that each got.

#1982 Add Scalafix migration for Cats Effect 2.4.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#1983 Tweak URL for the Cats Effect 2.4.0 Scalafix migration
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#1981 Added support for GitLab draft MRs
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/MergeRequestPayloadTest.scala
Labels: enhancement

#1987 Ignore ancient commons-beanutils versions
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Labels: enhancement

#1988 Update http4s-circe, http4s-client, ... to 0.21.20
  project/Dependencies.scala
Labels: dependency-update

#1989 add jwt-scala in artifact-migrations.conf
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#1990 Prevent overtaking updates
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: bug

#1991 Ignore build roots that contain '..'
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: enhancement

#1992 Also remove overtaking updates after ensuring that updates are fresh
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
Labels: bug

#1899 Add config key for default maven repo and self check url
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
Labels: enhancement

#1994 Do not use sbt's logger to print stewardDependencies
  modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala
Labels: bug

#1998 Update sbt to 1.4.8
  project/build.properties
Labels: dependency-update

#1999 Update sbt to 1.4.9
  project/build.properties
Labels: dependency-update

#2001 Update sbt-ci-release to 1.5.6
  project/plugins.sbt
Labels: dependency-update

#2002 Update coursier, coursier-cats-interop to 2.0.13
  project/Dependencies.scala
Labels: dependency-update

#2003 Do not make BuildToolDispatcher a subclass of BuildToolAlg
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
Labels: refactoring

#2004 BuildToolDispatcher: combine getBuildRoots and findBuildTools
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
Labels: refactoring

#2005 Parse RepoConfig only once
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
Labels: refactoring

#2006 Remove BuildToolDispatcher#getAdditionalDependencies
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
Labels: refactoring

#2007 Update sbt-native-packager to 1.8.1
  project/plugins.sbt
Labels: dependency-update

#2008 Update sbt-tpolecat to 0.1.17
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  project/plugins.sbt
Labels: dependency-update

#2009 Update coursier, coursier-cats-interop to 2.0.14
  project/Dependencies.scala
Labels: dependency-update

#2010 Improve the performance of Version.Component.parse
  .github/workflows/ci.yml
  build.sbt
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/VersionBenchmark.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  project/plugins.sbt
Labels: refactoring

#2012 Implement Version.Component.parse with cats-parse
  build.sbt
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/VersionBenchmark.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  project/Dependencies.scala
Labels: refactoring

#2013 Use cats.parse.SemVer for our SemVer.parse
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/data/SemVer.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/test/scala/org/scalasteward/core/data/SemVerTest.scala
  project/Dependencies.scala
Labels: refactoring

#2015 Fix imports in core/initialCommands
  build.sbt
Labels: build

#2014 Improve performance of Version.startsWithDate
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/VersionBenchmark.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
Labels: refactoring

#2016 Fix warnings about unused moduleRootPkg key
  build.sbt
Labels: build

#2017 Clean up VCSRepoAlg
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: refactoring

#2018 artifact-migrations.conf: slick-migration-api[-flyway]
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2020 Update coursier, coursier-cats-interop to 2.0.15
  project/Dependencies.scala
Labels: dependency-update

#2021 Update cats-effect to 2.4.0
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  project/Dependencies.scala
Labels: dependency-update

#1940 Add Scalafix migration for Cats Effect 3.0.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#2022 Update sbt-ci-release to 1.5.7
  project/plugins.sbt
Labels: dependency-update

#2024 Update coursier, coursier-cats-interop to 2.0.16
  project/Dependencies.scala
Labels: dependency-update

#2025 Update log4cats-slf4j to 1.2.1
  project/Dependencies.scala
Labels: dependency-update

#2027 Update formatting for Scala 3
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
Labels: refactoring

#2031 Use an immutable reference for the Cats Effect 2.4.0 migration
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#2032 Update http4s-circe, http4s-client, ... to 0.21.21
  project/Dependencies.scala
Labels: dependency-update

#2036 Update munit, munit-scalacheck to 0.7.23
  project/Dependencies.scala
Labels: dependency-update

#2037 Update discipline-munit to 1.0.7
  project/Dependencies.scala
Labels: dependency-update

#2035 Update sbt-scalafix to 0.9.27
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#2039 Update cats-core, cats-laws to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#2040 Update refined, refined-scalacheck to 0.9.22
  project/Dependencies.scala
Labels: dependency-update

#2041 Update cats-effect to 2.4.1
  project/Dependencies.scala
Labels: dependency-update

#2044 Update fs2-core, fs2-io to 2.5.4
  project/Dependencies.scala
Labels: dependency-update

#2046 Update atto-core to 0.9.3
  project/Dependencies.scala
Labels: dependency-update
