Repository scala-steward-org/scala-steward, pull requests merged in 2021-12, with the labels that each got.

#2389 Update bcprov-jdk15to18 to 1.70
  project/Dependencies.scala
Labels: dependency-update

#2391 Update sbt-github-actions to 0.14.0
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
  project/plugins.sbt
Labels: dependency-update

#2393 Update sbt-github-actions to 0.14.2
  project/plugins.sbt
Labels: dependency-update

#2394 Update scalafmt-core to 3.2.1
  .scalafmt.conf
Labels: dependency-update

#2396 Update sbt-scalafmt to 2.4.5
  project/plugins.sbt
Labels: dependency-update

#2398 Update munit-cats-effect-3 to 1.0.7
  project/Dependencies.scala
Labels: dependency-update

#2399 Update fs2-core, fs2-io to 3.2.3
  project/Dependencies.scala
Labels: dependency-update

#2395 Add `commit-count` label to PR bodies
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#2404 Update sbt to 1.5.6
  project/build.properties
Labels: dependency-update

#2401 Update http4s-circe, http4s-client, ... to 1.0.0-M30
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  project/Dependencies.scala
Labels: dependency-update

#2407 Update logback-classic to 1.2.8
  project/Dependencies.scala
Labels: dependency-update

#2409 Update sbt to 1.5.7
  project/build.properties
Labels: dependency-update

#2411 Update logback-classic to 1.2.9
  project/Dependencies.scala
Labels: dependency-update

#2413 Update mill-scalalib to 0.9.11
  project/Dependencies.scala
Labels: dependency-update

#2417 Update cats-effect to 3.3.1
  project/Dependencies.scala
Labels: dependency-update

#2419 Update sbt to 1.5.8
  project/build.properties
Labels: dependency-update

#2414 Replace case-app with decline
  build.sbt
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/Main.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/util/dateTime.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSType.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
  modules/docs/mdoc/help.md
  project/Dependencies.scala
Labels: enhancement

#2420 Update decline to 2.2.0
  project/Dependencies.scala
Labels: dependency-update

#2421 Add `takeUntilMaybe` and inline `NurtureAlg.processUpdates`
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
Labels: refactoring

#2423 Update logback-classic to 1.2.10
  project/Dependencies.scala
Labels: dependency-update

#2425 Do not run scalafmt with `--quiet`
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
Labels: enhancement

#2426 Update scalafmt-core to 3.2.2
  .scalafmt.conf
Labels: dependency-update

#2427 Change return type of `PruningAlg#needsAttention`
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: refactoring

#2431 Update fs2-core, fs2-io to 3.2.4
  project/Dependencies.scala
Labels: dependency-update

#2432 Update sbt-scalafmt to 2.4.6
  project/plugins.sbt
Labels: dependency-update

#2433 Update scalafmt-core to 3.3.0
  .scalafmt.conf
Labels: dependency-update

#2429 Disable progress to potentially speed up on multi-module project
  build.sbt
Labels: enhancement

#2442 Update cats-effect to 3.3.2
  project/Dependencies.scala
Labels: dependency-update
