Repository scala-steward-org/scala-steward, pull requests merged in 2022-12, with the labels that each got.

#2807 Add note to default config files that are downloaded at start-up
  modules/core/src/main/resources/artifact-migrations.v2.conf
  modules/core/src/main/resources/default.scala-steward.conf
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: documentation

#2809 Update cats-effect to 3.4.2
  project/Dependencies.scala
Labels: dependency-update

#2808 Update logback-classic to 1.4.5
  project/Dependencies.scala
Labels: dependency-update

#2813 Bump JDK versions in Mergify config
  .mergify.yml
Labels: build

#2812 Update mill-scalalib to 0.10.10
  project/Dependencies.scala
Labels: dependency-update

#2815 Update sbt-assembly to 2.1.0
  project/plugins.sbt
Labels: dependency-update

#2810 Add Bitbucket default reviewers option
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/CreatePullRequestRequest.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/Reviewer.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/Url.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
Labels: enhancement

#2820 fix(maven): exclude transitive deps for Maven
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/command.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
Labels: bug

#2824 Use scalaStewardMillPluginArtifactName in scalaStewardMillPlugin
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  project/Dependencies.scala
  repos.md
Labels: build

#2826 Update scala-steward-mill-plugin_mill0.10_2.13 to 0.17.1
  project/Dependencies.scala
Labels: dependency-update

#2828 Update coursier to 2.1.0-RC3
  project/Dependencies.scala
Labels: dependency-update

#2827 Add Alejandro to the list of maintainers
  build.sbt
Labels: administration

#2829 Make dummy a cross project
  .github/workflows/ci.yml
  build.sbt
Labels: build

#2830 Remove unused `FileAlg#writeFileData`
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
Labels: refactoring

#2831 Add artifact migration for sbt-ghpages
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#2832 Update decline to 2.4.1
  project/Dependencies.scala
Labels: dependency-update

#2833 Use `Sync[F].blocking` for creating system processes
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
Labels: refactoring

#2834 Update coursier to 2.1.0-RC3-1
  project/Dependencies.scala
Labels: dependency-update

#2835 Update http4s-blaze-server to 1.0.0-M37
  project/Dependencies.scala
Labels: dependency-update

#2837 Azure repos support
  README.md
  docs/help.md
  docs/running.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSType.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/azurerepos/AzureReposApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/azurerepos/JsonCodec.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/azurerepos/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/azurerepos/authentication.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/azurerepos/UrlTest.scala
  modules/docs/mdoc/running.md
Labels: enhancement

#2842 Update links to Scalafix documentation
  docs/scalafix-migrations.md
  modules/docs/mdoc/scalafix-migrations.md
Labels: documentation

#2840 Warn about missing Scalafix support in MillAlg and MavenAlg
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
Labels: documentation

#2845 Update coursier to 2.1.0-RC4
  project/Dependencies.scala
Labels: dependency-update

#2846 Make `findUpdate` and `migrateArtifactId` private
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
Labels: refactoring

#2843 Revamp documentation about artifact migrations
  docs/artifact-migrations.md
  docs/scalafix-migrations.md
  modules/docs/mdoc/artifact-migrations.md
  modules/docs/mdoc/scalafix-migrations.md
Labels: documentation

#2849 Let Scalafmt format Scaladocs
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Scope.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestGroup.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateFilter.scala
  modules/core/src/main/scala/org/scalasteward/core/util/Change.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/RepositoryResponse.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubAppApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubAuthAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
Labels: refactoring

#2850 Update README.md -> Community
  README.md
Labels: administration

#2851 Add node/yarn to the docker image
  build.sbt
Labels: build

#2852 Add sbt plugins locally and not globally
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
Labels: enhancement

#2853 Merge ConfigParsingResult and ConfigValidationResult
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/ValidateRepoConfigAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: refactoring

#2855 Test JsonKeyValueStore#get with malformed JSON
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
Labels: testing

#2856 Update cats-effect to 3.4.3
  project/Dependencies.scala
Labels: dependency-update

#2854 Log when a build tool is called for getting dependencies
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockWorkspaceAlg.scala
Labels: refactoring

#2858 Show that our sbt plugin requires at least 1.3.11
  build.sbt
Labels: build

#2859 Use a version dependent sbt plugin
  .github/workflows/ci.yml
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/data/SbtVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/parser.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala
  modules/sbt-plugin-1_0_0/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin_1_0_0.scala
  modules/sbt-plugin-1_3_11/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin_1_3_11.scala
Labels: bug, build

#2861 Do not overwrite version scheme for scala-xml
  project/plugins.sbt
  repos.md
Labels: build

#2860 Use sbt plugins from scala-steward-org/sbt-plugin repo
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/sbt-plugin-1_0_0/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin_1_0_0.scala
  modules/sbt-plugin-1_3_11/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin_1_3_11.scala
Labels: build

#2816 Untangle `UpdateHeuristic` into separate tasks
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/ModulePositionScanner.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/ScannerAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/VersionPositionScanner.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/data/ModulePosition.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/data/Substring.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/data/VersionPosition.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/package.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/util/Change.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/editTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/update/ModulePositionScannerTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/update/VersionPositionScannerTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/ChangeTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
Labels: enhancement

#2865 Update cats-effect to 3.4.4
  project/Dependencies.scala
Labels: dependency-update

#2864 Optimize regexes in VersionPositionScanner
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/VersionPositionScannerBenchmark.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/VersionPositionScanner.scala
Labels: refactoring

#2868 More faitful implementation of `coursier.util.Sync#schedule`
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/package.scala
Labels: refactoring

#2867 Fuse stream transformations in `FileAlg#findFiles`
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
Labels: refactoring
