Repository scala-steward-org/scala-steward, pull requests merged in 2022-01, with the labels that each got.

#2444 Update cats-effect to 3.3.3
  project/Dependencies.scala
Labels: dependency-update

#2445 Update scalafmt-core to 3.3.1
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCache.scala
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinder.scala
Labels: dependency-update

#2451 Ensure post update hooks having a `command` set via it's type
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: enhancement

#2453 Make RepoConfig.postUpdateHooks optional
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: refactoring

#2454 Update mill-scalalib to 0.9.12
  project/Dependencies.scala
Labels: dependency-update

#2456 Update cats-effect to 3.3.4
  project/Dependencies.scala
Labels: dependency-update

#2460 Update sbt-scalafix to 0.9.34
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  project/plugins.sbt
Labels: dependency-update

#2440 Update sbt to 1.6.1
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
  project/build.properties
Labels: dependency-update

#2463 Update scala-library to 2.13.8
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
Labels: dependency-update

#2464 Update mill-scalalib to 0.10.0
  project/Dependencies.scala
Labels: dependency-update

#2466 Add artifact migration for cakemix
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2469 Update scalafmt-core to 3.3.2
  .scalafmt.conf
Labels: dependency-update

#2449 Revert "Revert "Add artifact migration for sbt-twirl""
  modules/core/src/main/resources/artifact-migrations.conf
Labels: artifact-migration

#2472 Add initialVersion again to artifact-migrations.conf
  modules/core/src/main/resources/artifact-migrations.conf
Labels: bug

#2473 Update scalafmt-core to 3.3.3
  .scalafmt.conf
Labels: dependency-update

#2470 Refactor UpdateAlg
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinder.scala
  modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
Labels: refactoring

#2476 add scalatestplus testng in `artifact-migrations.v2.conf`
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#2477 Use more test syntax in CoursierAlg
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
Labels: testing, refactoring

#2475 dynamic sbt-scalafix version
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  project/plugins.sbt
Labels: enhancement

#2482 Minor refactorings
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillDepParserTest.scala
Labels: refactoring

#2480 Add all maintainers to the `developers` setting
  build.sbt
Labels: administration

#2485 Remove constant string from repo config parsing error
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigLoader.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: enhancement

#2481 Rename `master` to `main`
  .github/workflows/ci.yml
  build.sbt
  docs/artifact-migrations.md
  docs/faq.md
  docs/running.md
  docs/scalafix-migrations.md
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
Labels: administration

#2484 Use Version in Dependency and Update
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/UpdatesConfigBenchmark.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinder.scala
  modules/core/src/main/scala/org/scalasteward/core/git/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillVersionParserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: refactoring

#2487 Parallelize `UpdateAlg.findUpdates`
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
Labels: enhancement

#2489 Update mdoc, sbt-mdoc to 2.3.0
  project/plugins.sbt
Labels: dependency-update

#2488 Add artifact migration for sbt-play-ebean
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#2490 Update scalafmt-core to 3.4.0
  .scalafmt.conf
Labels: dependency-update

#2491 Update cats-effect to 3.3.5
  project/Dependencies.scala
Labels: dependency-update

#2494 Update coursier to 2.1.0-M3
  project/Dependencies.scala
Labels: dependency-update
