Repository scala-steward-org/scala-steward, pull requests merged in 2022-06, with the labels that each got.

#2621 Do not advertize scala-steward-org/repos in repos.md
  repos.md
Labels: documentation

#2623 Update sbt-tpolecat to 0.3.3
  project/plugins.sbt
Labels: dependency-update

#2625 Update scalafmt-core to 3.5.8
  .scalafmt.conf
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
Labels: dependency-update

#2626 Use the current artifact migrations file in MockContext
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Labels: testing

#2631 Update fs2-core, fs2-io to 3.2.8
  project/Dependencies.scala
Labels: dependency-update

#2538 SBT plugin: Find credentials by realms if possible
  modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala
Labels: bug

#2523 Add support for PR labels
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubLabels.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/MergeRequestPayloadTest.scala
Labels: enhancement

#2633 Bump jjwt-api
  build.sbt
  project/Dependencies.scala
Labels: dependency-update

#2540 Retry on Retry-After response header
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
  modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala
Labels: enhancement

#2605 Scan project/project/... folders
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
Labels: enhancement

#2622 Warn if repos.md is not properly formatted
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
Labels: enhancement

#2639 Tag latest docker image with latest-release
  build.sbt
Labels: build

#2641 Update decline to 2.3.0
  project/Dependencies.scala
Labels: dependency-update

#2642 Update cats-core, cats-laws to 2.8.0
  project/Dependencies.scala
Labels: dependency-update

#2643 Update log4cats-slf4j to 2.3.2
  project/Dependencies.scala
Labels: dependency-update

#2646 Update refined, refined-scalacheck to 0.10.0
  project/Dependencies.scala
Labels: dependency-update

#2647 Update sbt-scoverage to 2.0.0
  project/plugins.sbt
Labels: dependency-update

#2632 Update scala-library to 2.12.16
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
Labels: dependency-update

#2624 Update http4s-blaze-server, http4s-circe, ... to 1.0.0-M33
  project/Dependencies.scala
Labels: dependency-update

#2649 Add sha1 field to Commit case class
  modules/core/src/main/scala/org/scalasteward/core/git/Commit.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: refactoring
