Repository scala-steward-org/scala-steward, pull requests merged in 2022-11, with the labels that each got.

#2757 Update scalafmt-core to 3.6.1
  .scalafmt.conf
Labels: dependency-update

#2756 Update sbt to 1.7.3
  .github/workflows/ci.yml
  project/build.properties
Labels: dependency-update

#2761 Update coursier to 2.1.0-RC1
  project/Dependencies.scala
Labels: dependency-update

#2760 Update mill-scalalib to 0.10.9
  project/Dependencies.scala
Labels: dependency-update

#2766 Update cats-core, cats-laws to 2.9.0
  project/Dependencies.scala
Labels: dependency-update

#2765 Update sbt-scalafmt to 2.5.0
  project/plugins.sbt
Labels: dependency-update

#2764 Update sbt to 1.8.0
  project/build.properties
Labels: dependency-update

#2769 Update coursier to 2.1.0-RC2
  project/Dependencies.scala
Labels: dependency-update

#2768 Update sbt-header to 5.9.0
  project/plugins.sbt
Labels: dependency-update

#2767 Update cats-effect to 3.4.0
  project/Dependencies.scala
Labels: dependency-update

#2781 Increase coverage
  modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
Labels: administration

#2782 Remove twitter account
  README.md
Labels: administration

#2784 Update cats-effect to 3.4.1
  project/Dependencies.scala
Labels: dependency-update

#2783 Update decline to 2.4.0
  project/Dependencies.scala
Labels: dependency-update

#2748 Rename the `AnUpdate` hierarchy
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/UpdatesConfigBenchmark.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/data/UpdateData.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAttempt.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/PostUpdateHook.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinder.scala
  modules/core/src/main/scala/org/scalasteward/core/git/CommitMsg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/package.scala
  modules/core/src/main/scala/org/scalasteward/core/io/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/GroupRepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestGroup.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateFilter.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
  modules/core/src/main/scala/org/scalasteward/core/update/show.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
  modules/core/src/test/scala/org/scalasteward/core/data/GroupedUpdateTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/gitTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: refactoring

#2779 Replace Java 8 with newer LTS Java 17
  .github/workflows/ci.yml
  build.sbt
Labels: dependency-update

#2786 Update scalacache-caffeine to 1.0.0-M6
  modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
  project/Dependencies.scala
Labels: dependency-update

#2788 Update logback-classic to 1.3.5
  project/Dependencies.scala
Labels: dependency-update

#2791 Update fs2-core, fs2-io to 3.4.0
  project/Dependencies.scala
Labels: dependency-update

#2792 Add Mobimeo & ybasket to Readme
  README.md
Labels: documentation

#2800 Add commented java options for remote debugging
  build.sbt
Labels: build

#2804 Scalafix artifactId patterns must match whole artifactIds
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinder.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinderTest.scala
Labels: bug
