Repository scala-steward-org/scala-steward, pull requests merged in 2022-10, with the labels that each got.

#2721 Update decline to 2.3.1
  project/Dependencies.scala
Labels: dependency-update

#2720 Update fs2-core, fs2-io to 3.3.0
  project/Dependencies.scala
Labels: dependency-update

#2722 Update circe-generic, circe-literal, ... to 0.14.3
  project/Dependencies.scala
Labels: dependency-update

#2724 Update bcprov-jdk15to18 to 1.72
  project/Dependencies.scala
Labels: dependency-update

#2729 Update scalacheck to 1.17.0
  project/Dependencies.scala
Labels: dependency-update

#2728 Update sbt to 1.7.2
  project/build.properties
Labels: dependency-update

#2730 Update mdoc, sbt-mdoc to 2.3.6
  project/plugins.sbt
Labels: dependency-update

#2732 Update log4cats-slf4j to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#2725 Update http4s-circe, http4s-client, ... to 1.0.0-M37
  project/Dependencies.scala
Labels: dependency-update

#2737 Update sbt-scoverage to 2.0.4
  project/plugins.sbt
Labels: dependency-update

#2731 Update sbt-scoverage to 2.0.4
  project/plugins.sbt
Labels: dependency-update

#2738 Update to scala-library to 2.12.17
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
Labels: dependency-update

#2742 Update coursier to 2.1.0-M7
  build.sbt
  project/Dependencies.scala
Labels: dependency-update

#2723 Update coursier to 2.1.0-M7
  project/Dependencies.scala
Labels: dependency-update

#2741 Update to scoverage to 2.0.5
  project/plugins.sbt
Labels: dependency-update

#2740 Update to scala-library to 2.13.10
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
Labels: dependency-update

#2743 Update sbt-native-packager to 1.9.11
  project/plugins.sbt
Labels: dependency-update

#2745 Update logback-classic only on 1.3.x series that supports JDK 8
  .scala-steward.conf
Labels: administration

#2714 Add support for grouping dependency updates
  build.sbt
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/data/SemVer.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/data/UpdateData.scala
  modules/core/src/main/scala/org/scalasteward/core/git/CommitMsg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/GroupRepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestGroup.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateFilter.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/data/GroupedUpdateTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: enhancement

#2528 feat: Adding support for setting required number of reviewers on a S…
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/Url.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Labels: enhancement

#2750 Update sbt-ci-release to 1.5.11
  project/plugins.sbt
Labels: dependency-update

#2751 Update mill-scalalib to 0.10.8
  project/Dependencies.scala
Labels: dependency-update

#2749 Update sbt-assembly to 2.0.0
  project/plugins.sbt
Labels: dependency-update

#2752 Update sbt-header to 5.8.0
  project/plugins.sbt
Labels: dependency-update

#2753 Update circe-generic-extras to 0.14.3
  project/Dependencies.scala
Labels: dependency-update

#2754 Update scalafmt-core to 3.6.0
  .scalafmt.conf
Labels: dependency-update

#2755 Update sbt-scoverage to 2.0.6
  project/plugins.sbt
Labels: dependency-update
