Repository scala-steward-org/scala-steward, pull requests merged in 2022-07, with the labels that each got.

#2650 Update mill-scalalib to 0.10.5
  project/Dependencies.scala
Labels: dependency-update

#2651 Update cats-effect to 3.3.13
  project/Dependencies.scala
Labels: dependency-update

#2609 Update circe-generic, circe-literal, ... to 0.14.2
  project/Dependencies.scala
Labels: dependency-update

#2653 Update fs2-core, fs2-io to 3.2.9
  project/Dependencies.scala
Labels: dependency-update

#2654 Add post-update hook for sbt-header
  modules/core/src/main/resources/default.scala-steward.conf
Labels: enhancement

#2652 Add reformatting commits to .git-blame-ignore-revs
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAttempt.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/PostUpdateHook.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
Labels: enhancement

#2495 Move sbt-java-formatter hook to `default.scala-steward.conf`
  modules/core/src/main/resources/default.scala-steward.conf
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/git/CommitMsg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/package.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
Labels: enhancement

#2655 Add command to the commit message of post-update hooks
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/git/CommitMsg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
Labels: enhancement

#2648 Change commit message of hook that runs 'sbt githubWorkflowGenerate'
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
Labels: enhancement

#2656 Update cats-parse to 0.3.8
  project/Dependencies.scala
Labels: dependency-update

#2657 Update refined, refined-scalacheck to 0.10.1
  project/Dependencies.scala
Labels: dependency-update

#2658 Update http4s-circe, http4s-client, ... to 1.0.0-M34
  project/Dependencies.scala
Labels: dependency-update

#2661 Check that sbt.parser also parses the scalaVersion field
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala
Labels: testing

#2663 Update fs2-core, fs2-io to 3.2.10
  project/Dependencies.scala
Labels: dependency-update

#2666 Update sbt to 1.7.1
  .github/workflows/ci.yml
  project/build.properties
Labels: dependency-update

#2669 Update cats-effect to 3.3.14
  project/Dependencies.scala
Labels: dependency-update

#2670 Update log4cats-slf4j to 2.4.0
  project/Dependencies.scala
Labels: dependency-update

#2672 Update sbt-tpolecat to 0.4.0
  project/plugins.sbt
Labels: dependency-update

#2676 Update sbt-tpolecat to 0.4.1
  project/plugins.sbt
Labels: dependency-update

#2665 Advertize VirtusLab's public Scala Steward instance
  README.md
  repos.md
Labels: administration

#2680 Update mdoc, sbt-mdoc to 2.3.3
  project/plugins.sbt
Labels: dependency-update

#2678 Update fs2-core, fs2-io to 3.2.11
  project/Dependencies.scala
Labels: dependency-update

#2679 Update http4s-circe, http4s-client, ... to 1.0.0-M35
  project/Dependencies.scala
Labels: dependency-update

#2683 Update http4s-blaze-server to 1.0.0-M35
  project/Dependencies.scala
Labels: dependency-update

#2684 Add trace4cats artifact and scalafix migrations
  modules/core/src/main/resources/artifact-migrations.v2.conf
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration, artifact-migration

#2685 Add missing t4c artifact migrations
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration
