Repository scala-steward-org/scala-steward, pull requests merged in 2022-03, with the labels that each got.

#2543 Fix ignored test assertion
  modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala
Labels: testing

#2544 Update logback-classic to 1.2.11
  project/Dependencies.scala
Labels: dependency-update

#2545 Add artifact migration for sbt-git
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#2546 Update cats-effect to 3.3.7
  project/Dependencies.scala
Labels: dependency-update

#2547 Update mill-scalalib to 0.10.1
  project/Dependencies.scala
Labels: dependency-update

#2550 Update mill-scalalib to 0.10.2
  project/Dependencies.scala
Labels: dependency-update

#2551 Update http4s-blaze-server, http4s-circe, ... to 1.0.0-M32
  project/Dependencies.scala
Labels: dependency-update

#2552 Update cats-effect to 3.3.8
  project/Dependencies.scala
Labels: dependency-update

#2553 Update sbt-scalajs-crossproject to 1.2.0
  project/plugins.sbt
Labels: dependency-update

#2554 Update cats-effect to 3.3.9
  project/Dependencies.scala
Labels: dependency-update

#2555 Update sbt-doctest to 0.10.0
  project/plugins.sbt
Labels: dependency-update

#2556 Update mdoc, sbt-mdoc to 2.3.2
  project/plugins.sbt
Labels: dependency-update

#2557 Update fs2-core, fs2-io to 3.2.6
  project/Dependencies.scala
Labels: dependency-update

#2559 Update fs2-core, fs2-io to 3.2.7
  project/Dependencies.scala
Labels: dependency-update

#2560 Update sbt-tpolecat to 0.2.1
  project/plugins.sbt
Labels: dependency-update
