Repository scala-steward-org/scala-steward, pull requests merged in 2022-02, with the labels that each got.

#2496 Update coursier to 2.1.0-M3-1
  project/Dependencies.scala
Labels: dependency-update

#2499 Update sbt to 1.6.2
  project/build.properties
Labels: dependency-update

#2500 Update coursier to 2.1.0-M4
  project/Dependencies.scala
Labels: dependency-update

#2505 Update http4s-blaze-server, http4s-circe, ... to 1.0.0-M31
  project/Dependencies.scala
Labels: dependency-update

#2504 Reset update branch before merging the base branch
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
Labels: enhancement

#2506 Update scalafmt-core to 3.4.1
  .scalafmt.conf
Labels: dependency-update

#2507 Add RepositoryArchived exception
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubException.scala
Labels: enhancement

#2508 Update scalafmt-core to 3.4.2
  .scalafmt.conf
Labels: dependency-update

#2509 Add SecondaryRateLimitExceeded exception
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubException.scala
Labels: refactoring

#2511 Update coursier to 2.1.0-M4-1
  project/Dependencies.scala
Labels: dependency-update

#2512 Update sbt-header to 5.6.5
  project/plugins.sbt
Labels: dependency-update

#2514 Throw RepositoryArchived in createFork/getRepo
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/RepoOut.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubException.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
Labels: enhancement

#2516 Update coursier to 2.1.0-M5
  project/Dependencies.scala
Labels: dependency-update

#2517 Limit precision for human readability
  modules/core/src/main/scala/org/scalasteward/core/util/dateTime.scala
  modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
Labels: refactoring

#2522 Adapt the check for hashes in versions
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#2524 Update scalafmt-core to 3.4.3
  .scalafmt.conf
Labels: dependency-update

#2525 Update sbt-assembly to 1.1.1
  project/plugins.sbt
Labels: dependency-update

#2526 Update sbt-assembly to 1.2.0
  project/plugins.sbt
Labels: dependency-update

#2529 Update sbt-native-packager to 1.9.8
  project/plugins.sbt
Labels: dependency-update

#2530 Update sbt-buildinfo to 0.11.0
  project/plugins.sbt
Labels: dependency-update

#2531 Update sbt-tpolecat to 0.1.22
  project/plugins.sbt
Labels: dependency-update

#2532 Update fs2-core, fs2-io to 3.2.5
  project/Dependencies.scala
Labels: dependency-update

#2534 Update sbt-native-packager to 1.9.9
  project/plugins.sbt
Labels: dependency-update

#2535 Update coursier to 2.1.0-M5-5-g2cb552ea9
  project/Dependencies.scala
Labels: dependency-update

#2537 Update mdoc, sbt-mdoc to 2.3.1
  project/plugins.sbt
Labels: dependency-update

#2539 Update cats-effect to 3.3.6
  project/Dependencies.scala
Labels: dependency-update
