Repository scala-steward-org/scala-steward, pull requests merged in 2023-03, with the labels that each got.

#2999 Run Scala CLI with `--power`
  modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
Labels: bug, cat:build-tool

#3002 Update refined, refined-scalacheck to 0.10.2
  project/Dependencies.scala
Labels: dependency-update

#3003 Update circe-generic, circe-literal, ... to 0.14.5
  project/Dependencies.scala
Labels: dependency-update

#3004 Update sbt-typelevel-mergify to 0.4.19
  project/plugins.sbt
Labels: dependency-update

#3000 refactoring: remove ForgeApiAlg.labelPullRequest
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/JsonCodec.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/JsonCodecTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/UrlTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/MergeRequestPayloadTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
Labels: refactoring, cat:forge

#2994 Ignore file excluded from git
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/edit/update/ScannerAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  project/Dependencies.scala
Labels: enhancement

#3005 Allow to execute commands in MockEff
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
Labels: testing

#2995 Check up to 5 nested project folders
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
Labels: enhancement

#3007 #3006 Support for removing source branch on GitLab merge requests
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/MergeRequestPayloadTest.scala
Labels: enhancement, cat:forge

#3010 Adding artifact migrations for async-utils
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3019 Update refined, refined-scalacheck to 0.10.3
  project/Dependencies.scala
Labels: dependency-update

#3018 Update mill-main_2.13 to 0.10.12
  project/Dependencies.scala
Labels: dependency-update

#3017 Use Git's `--trailer` for commit message trailers
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/git/CommitMsg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
Labels: refactoring

#3016 Fixed throwing StringIndexOutOfBoundsException
  modules/core/src/main/scala/org/scalasteward/core/edit/update/data/Substring.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
Labels: bug, cat:rewrite

#3021 Update to changes in coursier 2.1.0
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  project/Dependencies.scala
Labels: dependency-update

#3022 Update scalafmt-core to 3.7.3
  .scalafmt.conf
Labels: dependency-update

#3012 Check merge request status with backoff
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala
Labels: enhancement, cat:forge
