Repository scala-steward-org/scala-steward, pull requests merged in 2023-02, with the labels that each got.

#2954 Update `.scalafmt.conf` and `.mill-version` also in subdirectories
  modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
Labels: bug

#2955 Update sbt-jmh to 0.4.4
  project/plugins.sbt
Labels: dependency-update

#2956 Update cats-effect to 3.4.6
  project/Dependencies.scala
Labels: dependency-update

#2959 Update circe-config to 0.9.0
  project/Dependencies.scala
Labels: dependency-update

#2961 Update circe-config to 0.10.0
  project/Dependencies.scala
Labels: dependency-update

#2960 Update better-files to 3.9.2
  project/Dependencies.scala
Labels: dependency-update

#2758 vcs: add gitea
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeType.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitea/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/package.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinder.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitea/UrlTest.scala
Labels: enhancement, cat:forge

#2964 Update circe-generic, circe-literal, ... to 0.14.4
  project/Dependencies.scala
Labels: dependency-update

#2965 Update http4s-jdk-http-client to 1.0.0-M9
  project/Dependencies.scala
Labels: dependency-update

#2967 Update sbt-native-packager to 1.9.14
  project/plugins.sbt
Labels: dependency-update

#2966 Update fs2-core, fs2-io to 3.6.1
  project/Dependencies.scala
Labels: dependency-update

#2968 Add `Sha1.unsafeFrom`
  modules/core/src/main/scala/org/scalasteward/core/git/Sha1.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/data/BranchOutTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
Labels: testing, refactoring

#2969 Update sbt-scoverage to 2.0.7
  modules/core/src/test/scala/org/scalasteward/core/edit/update/VersionPositionScannerTest.scala
  project/plugins.sbt
Labels: dependency-update

#2972 Update sbt-assembly to 2.1.1
  project/plugins.sbt
Labels: dependency-update

#2975 Update sbt-native-packager to 1.9.15
  project/plugins.sbt
Labels: dependency-update

#2978 Update cats-effect to 3.4.7
  project/Dependencies.scala
Labels: dependency-update

#2974 Use adoptopenjdk replacement temurin base image
  build.sbt
Labels: build

#2953 Add ability to add assignees and reviewers for GitLab and GitHub
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubAssignees.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubReviewers.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/Url.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/JsonCodecTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/UrlTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/MergeRequestPayloadTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: enhancement

#2980 github: add dedicated model for create PR body
  modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/PullRequestPayload.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/JsonCodecTest.scala
Labels: refactoring, cat:forge

#2983 Update sbt-native-packager to 1.9.16
  project/plugins.sbt
Labels: dependency-update

#2984 Update cats-effect to 3.4.8
  project/Dependencies.scala
Labels: dependency-update

#2989 Add test for closing standard input in `slurp`
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
Labels: testing

#2982 git check-ignore before adding
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
Labels: enhancement

#2990 Update scalafmt-core to 3.7.2
  .scalafmt.conf
Labels: dependency-update
