Repository scala-steward-org/scala-steward, pull requests merged in 2023-06, with the labels that each got.

#3066 Update scalafmt-core to 3.7.4
  .scalafmt.conf
Labels: dependency-update

#3067 sbt-javaagent is published to the com.github.sbt group ID
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3068 Update sbt to 1.9.0
  project/build.properties
Labels: dependency-update

#3070 Update sbt-scoverage to 2.0.8
  modules/core/src/test/scala/org/scalasteward/core/edit/update/VersionPositionScannerTest.scala
  project/plugins.sbt
Labels: dependency-update

#3072 Update sbt-typelevel-mergify to 0.4.22
  project/plugins.sbt
Labels: dependency-update

#3078 Update commons-io to 2.13.0
  project/Dependencies.scala
Labels: dependency-update

#3079 Update sbt-header to 5.10.0
  project/plugins.sbt
Labels: dependency-update

#3081 Update scala-steward-mill-plugin_mill0.10_2.13 to 0.18.0
  project/Dependencies.scala
Labels: dependency-update

#3077 Update mill-main_2.13 to 0.11.0
  project/Dependencies.scala
Labels: dependency-update

#3080 Update scala-library to 2.13.11
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
Labels: dependency-update

#3084 Update logback-classic to 1.4.8
  project/Dependencies.scala
Labels: dependency-update

#3089 Update gitignore to 0.6.0
  project/Dependencies.scala
Labels: dependency-update

#3090 Update refined, refined-scalacheck to 0.11.0
  project/Dependencies.scala
Labels: dependency-update

#3091 Update bcprov-jdk15to18 to 1.74
  project/Dependencies.scala
Labels: dependency-update

#3093 Add sbt.server.forcestart option to SbtAlg to allow for sbt compatibility versions < 1.7
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
Labels: bug, cat:build-tool

#3094 Update coursier, ... to 2.1.5
  project/Dependencies.scala
Labels: dependency-update

#3095 Different execution for mill 0.11
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
Labels: bug, cat:build-tool

#3099 Update bcprov-jdk15to18 to 1.75
  project/Dependencies.scala
Labels: dependency-update

#3100 Let Scala Steward send upgrades to Scala.js 1.13.2.
  modules/core/src/main/resources/default.scala-steward.conf
Labels: administration

#3106 Update cats-parse to 0.3.10
  project/Dependencies.scala
Labels: dependency-update

#3105 Update cats-effect to 3.5.1
  project/Dependencies.scala
Labels: dependency-update

#3104 Update sbt to 1.9.1
  project/build.properties
Labels: dependency-update

#3108 Update scalafmt-core to 3.7.5
  .scalafmt.conf
Labels: dependency-update

#3101 Ensure `mockRoot` test folder is always cleared before tests run
  build.sbt
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
Labels: testing
