Repository scala-steward-org/scala-steward, pull requests merged in 2023-01, with the labels that each got.

#2871 Add more tests for various vcs
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubAppApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Labels: testing

#2870 Issue #2866: add FEAT to pre-release identifiers
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: enhancement

#2872 Add pre-determined HTTP responses to `MockState`
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/package.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
Labels: testing

#2874 Remove sbt-crossproject workaround
  build.sbt
Labels: build

#2876 Update monocle-core to 3.2.0
  project/Dependencies.scala
Labels: dependency-update

#2879 Update sbt to 1.8.1
  project/build.properties
Labels: dependency-update

#2880 Update cats-parse to 0.3.9
  project/Dependencies.scala
Labels: dependency-update

#2875 Use `clientResponses` from `MockState` in vcs tests
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubAppApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Labels: testing

#2882 Update http4s-circe, http4s-client, ... to 1.0.0-M38
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala
  project/Dependencies.scala
Labels: dependency-update

#2881 Rename `WorkspaceAlg#cleanWorkspace`
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/WorkspaceAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockWorkspaceAlg.scala
Labels: refactoring

#2883 Update http4s-blaze-server to 1.0.0-M38
  project/Dependencies.scala
Labels: dependency-update

#2885 Update sbt to 1.8.2
  project/build.properties
Labels: dependency-update

#2886 Add a note to FAQ about persisting workspace
  docs/faq.md
  modules/docs/mdoc/faq.md
Labels: documentation

#2888 Replacing deprecated http4s-okhttp-client with http4s-jdk-http-client
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
  project/Dependencies.scala
Labels: refactoring

#2890 Use releaseNotesUrl even if repoUrl is empty
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
Labels: bug

#2891 Rename VCSExtraAlg to UpdateInfoUrlFinder
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrl.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinder.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Labels: refactoring

#2884 Issue #2877: Fix "Unable to bump version" when using a val version in libraryDependencies ++= Seq(...)
  modules/core/src/main/scala/org/scalasteward/core/edit/update/data/ModulePosition.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
Labels: bug

#2894 Use WorkspaceAlg#repoDir in tests
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/package.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Labels: testing, refactoring

#2895 Test RepoCacheAlg with an up-to-date cache
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/test/scala/org/scalasteward/core/repocache/RepoCacheAlgTest.scala
Labels: testing

#2896 Reuse compiled regex where possible
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/package.scala
  modules/core/src/main/scala/org/scalasteward/core/git/Author.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/Repo.scala
Labels: refactoring

#2897 unit tests for org.scalasteward.core.util.string
  modules/core/src/test/scala/org/scalasteward/core/util/stringTest.scala
Labels: testing

#2899 Prefer GitHub release notes over custom release notes
  modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrl.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinder.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinderTest.scala
Labels: enhancement

#2892 Update sbt-tpolecat to 0.4.2
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestOut.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/data/RepoOut.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillVersionParserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repocache/RepoCacheAlgTest.scala
  project/plugins.sbt
Labels: dependency-update

#2898 Support artifact migrations in `Update.ForGroupId`
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
  modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
  modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
Labels: bug

#2901 Test `HttpJsonClient#getAll`
  modules/core/src/test/scala/org/scalasteward/core/util/HttpJsonClientTest.scala
Labels: testing

#2900 Use sbt-typelevel-mergify to generate `.mergify.yml`
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
  project/plugins.sbt
Labels: build

#2909 Rename and test JsonParseError
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/test/scala/org/scalasteward/core/util/HttpJsonClientTest.scala
Labels: testing, refactoring

#2910 HttpJsonClient: unify client calls
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/test/scala/org/scalasteward/core/util/HttpJsonClientTest.scala
Labels: refactoring

#2914 Add sbt-github-actions artifact migration
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#2913 Implement HttpJsonClient#getAll as fs2.Stream
  modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
  modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubAppApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/util/HttpJsonClientTest.scala
Labels: refactoring

#2918 Simplify implementation of `findArtifactChange`
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinder.scala
Labels: refactoring

#2919 Do forge authentication in one function
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/authentication.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/bitbucket/authentication.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/authentication.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/authentication.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/authenticationTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
Labels: refactoring

#2921 Change Context.printBanner to a field
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
Labels: refactoring

#2920 Authenticate UrlChecker calls to API host
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/ForgeSelectionTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/authenticationTest.scala
Labels: enhancement

#2926 Update sbt-native-packager to 1.9.12
  project/plugins.sbt
Labels: dependency-update

#2929 Update cats-effect to 3.4.5
  project/Dependencies.scala
Labels: dependency-update

#2927 Use `30 days` instead of `@monthly` in repo config example
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/GroupRepoConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
Labels: enhancement

#2930 Update fs2-core, fs2-io to 3.5.0
  project/Dependencies.scala
Labels: dependency-update

#2932 Update sbt-native-packager to 1.9.13
  project/plugins.sbt
Labels: dependency-update

#2931 Support Maven dependencies with a property for the Scala binary suffix
  modules/core/src/main/scala/org/scalasteward/core/edit/update/ModulePositionScanner.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
Labels: enhancement

#2935 Update scalafmt-core to 3.7.0
  .scalafmt.conf
Labels: dependency-update

#2933 Extract dependencies from scala-cli via sbt export
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
  repos.md
Labels: enhancement, cat:build-tool

#2922 Add `ForgeSpecificCfg` trait
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
Labels: refactoring

#2937 Update coursier to 2.1.0-RC5
  project/Dependencies.scala
Labels: dependency-update

#2938 add mysql-connector-j in artifact-migrations
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#2940 Throw if slurp reads more lines than `max-buffer-size`
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixCli.scala
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/package.scala
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
Labels: enhancement

#2941 Update scalafmt-core to 3.7.1
  .scalafmt.conf
Labels: dependency-update

#2943 Update GitLab example
  docs/running.md
  modules/docs/mdoc/running.md
Labels: documentation

#2944 Update mill-main_2.13 to 0.10.11
  project/Dependencies.scala
Labels: dependency-update

#2945 Update http4s-circe, http4s-client, ... to 1.0.0-M39
  project/Dependencies.scala
Labels: dependency-update

#2949 Update mdoc, sbt-mdoc to 2.3.7
  project/plugins.sbt
Labels: dependency-update

#2951 Simplify ProcessAlg
  modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
Labels: refactoring
