Repository scala-steward-org/scala-steward, pull requests merged in 2023-07, with the labels that each got.

#3116 Update sbt-tpolecat to 0.4.4
  project/plugins.sbt
Labels: dependency-update

#3118 Update sbt to 1.9.2
  project/build.properties
Labels: dependency-update

#3117 Update sbt-scalajs-crossproject to 1.3.2
  project/plugins.sbt
Labels: dependency-update

#3119 Update scalafmt-core to 3.7.9
  .scalafmt.conf
Labels: dependency-update

#3122 Update scalafmt-core to 3.7.10
  .scalafmt.conf
Labels: dependency-update

#3125 Improve error message on overlong lines in `process.slurp`
  modules/core/src/main/scala/org/scalasteward/core/io/process.scala
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
Labels: enhancement

#3126 Add a Scalafix migration for sbt-tpolecat v0.5.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#3128 Update sbt to 1.9.3
  project/build.properties
Labels: dependency-update

#3131 Update sbt-tpolecat to 0.5.0
  project/plugins.sbt
Labels: dependency-update

#3132 Update scalafmt-core to 3.7.11
  .scalafmt.conf
Labels: dependency-update
