Repository scala-steward-org/scala-steward, pull requests merged in 2023-12, with the labels that each got.

#3229 Update logback-classic to 1.4.14
  project/Dependencies.scala
Labels: dependency-update

#3230 Update commons-io to 2.15.1
  project/Dependencies.scala
Labels: dependency-update

#3231 Update sbt-typelevel-mergify to 0.6.3
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependency-update

#3233 Use sbt-tpolecat's DevMode if CI env var is not set
  build.sbt
Labels: build

#3235 Add `toolkit` to list of scala-cli directives
  modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
Labels: enhancement

#3234 Use default resolver in `MillAlg`
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
Labels: enhancement

#3238 Remove `-Xfatal-warnings` comment
  build.sbt
Labels: build

#3240 Add links to PRs labelled with `artifact-migrations`
  docs/artifact-migrations.md
  docs/help.md
  docs/scalafix-migrations.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/docs/mdoc/artifact-migrations.md
  modules/docs/mdoc/scalafix-migrations.md
Labels: documentation

#3242 Update sbt-jmh to 0.4.7
  project/plugins.sbt
Labels: dependency-update

#3243 Minimize diff to BSP branch
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
Labels: refactoring

#3244 Add default implementation for `BuildToolAlg#runMigration`
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
Labels: refactoring

#3245 Update sbt to 1.9.8
  project/build.properties
Labels: dependency-update

#3246 Update sbt-typelevel-mergify to 0.6.4
  project/plugins.sbt
Labels: dependency-update

#3248 Update short description of Scala Steward
  README.md
Labels: documentation

#3247 Remove `StewardContext` hierarchy
  build.sbt
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/Main.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/application/ValidateRepoConfigContext.scala
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/ValidateRepoConfigAlgTest.scala
Labels: refactoring

#3251 `play-grpc` changed groupid to `org.playframework`
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3250 Do not cache the output of `gitAskPass`
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeAuthAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
Labels: enhancement

#3253 Document how to control Scala updates
  docs/faq.md
  modules/docs/mdoc/faq.md
Labels: documentation

#3254 Rename `otel4s-java*` to `otel4s-oteljava*`
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3252 Remove repo from function for modifying requests
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala
Labels: refactoring

#3255 Move `Encoder[Uri]` to `util.uri`
  modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/util/uri.scala
Labels: refactoring

#3256 Ignore circe-yaml 1.15.0
  modules/core/src/main/resources/default.scala-steward.conf
Labels: administration
