Repository scala-steward-org/scala-steward, pull requests merged in 2023-05, with the labels that each got.

#3044 Migrate `org.fluentlenium` to `io.fluentlenium`
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3045 Update sbt-ci-release to 1.5.12
  project/plugins.sbt
Labels: dependency-update

#3046 Update coursier, ... to 2.1.3
  project/Dependencies.scala
Labels: dependency-update

#3033 Add support for multiple configuration file locations
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: enhancement

#3050 Update cats-effect to 3.4.11
  project/Dependencies.scala
Labels: dependency-update

#3053 Migration for sbt-pom-reader
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3057 Update commons-io to 2.12.0
  project/Dependencies.scala
Labels: dependency-update

#3056 Update sbt-explicit-dependencies to 0.3.1
  project/plugins.sbt
Labels: dependency-update

#3061 Update sbt-typelevel-mergify to 0.4.21
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependency-update

#3059 Update sbt to 1.8.3
  project/build.properties
Labels: dependency-update

#3065 Update scala3-library to 3.3.0
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
Labels: dependency-update
