Repository scala-steward-org/scala-steward, pull requests merged in 2023-04, with the labels that each got.

#3024 Don't install Coursier via `git.io/coursier-cli`
  build.sbt
Labels: build

#3023 Remove duplication around `TraceEntry.Cmd` instances
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/ForgeRepoAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
Labels: testing, refactoring

#3025 Update sbt-scalajs-crossproject to 1.3.0
  project/plugins.sbt
Labels: dependency-update

#3028 Notify groupId change of sbt-sdlc
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3026 Migrate sbt-dynver to com.github.sbt
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3032 Update bcprov-jdk15to18 to 1.73
  project/Dependencies.scala
Labels: dependency-update

#3034 Update sbt-scalajs-crossproject to 1.3.1
  project/plugins.sbt
Labels: dependency-update

#3036 Update coursier, ... to 2.1.2
  project/Dependencies.scala
Labels: dependency-update

#3037 Update logback-classic to 1.4.7
  project/Dependencies.scala
Labels: dependency-update

#3038 Update log4cats-slf4j to 2.6.0
  project/Dependencies.scala
Labels: dependency-update

#3039 Update sbt-typelevel-mergify to 0.4.20
  project/plugins.sbt
Labels: dependency-update

#3042 Update cats-effect to 3.4.10
  project/Dependencies.scala
Labels: dependency-update
