Repository scala-steward-org/scala-steward, pull requests merged in 2023-11, with the labels that each got.

#3201 Update fs2-core, fs2-io to 3.9.3
  project/Dependencies.scala
Labels: dependency-update

#3202 Update sbt-typelevel-mergify to 0.6.1
  project/plugins.sbt
Labels: dependency-update

#3200 Add ncurses to the Docker image
  build.sbt
Labels: build

#3204 Update mdoc, sbt-mdoc to 2.5.0
  project/plugins.sbt
Labels: dependency-update

#3205 Update cats-parse to 1.0.0
  project/Dependencies.scala
Labels: dependency-update

#3203 Update circe-config to 0.10.1
  project/Dependencies.scala
Labels: dependency-update

#3208 Update mdoc, sbt-mdoc to 2.5.1
  project/plugins.sbt
Labels: dependency-update

#3207 Use correct start indices in ModulePositionScanner
  modules/core/src/main/scala/org/scalasteward/core/edit/update/ModulePositionScanner.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/update/ModulePositionScannerTest.scala
Labels: bug, cat:rewrite

#3212 Update sbt-typelevel-mergify to 0.6.2
  project/plugins.sbt
Labels: dependency-update

#3214 Update bcprov-jdk15to18 to 1.77
  project/Dependencies.scala
Labels: dependency-update

#3216 Update scalafmt-core to 3.7.17
  .scalafmt.conf
Labels: dependency-update

#3217 Update sbt-assembly to 2.1.5
  project/plugins.sbt
Labels: dependency-update

#3219 Reset instead of merge to update branches
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
Labels: enhancement

#3220 Update coursier, ... to 2.1.8
  project/Dependencies.scala
Labels: dependency-update

#3221 Add label for artifact migrations
  modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
Labels: enhancement

#3226 Update logback-classic to 1.4.13
  project/Dependencies.scala
Labels: dependency-update

#3188 support all scala-cli dependency directives
  README.md
  modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
Labels: enhancement

#3215 Use `GitAlg.findFilesContaining` in `ScannerAlg`
  .github/workflows/ci.yml
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/edit/update/ScannerAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
  project/Dependencies.scala
Labels: refactoring
