Repository scala-steward-org/scala-steward, pull requests merged in 2024-01, with the labels that each got.

#3259 Show repo owner in exception message
  modules/core/src/main/scala/org/scalasteward/core/forge/data/RepoOut.scala
Labels: refactoring

#3186 Update jjwt-api, jjwt-impl, jjwt-jackson to 0.12.3
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubAuthAlg.scala
  project/Dependencies.scala
Labels: dependency-update

#3260 Recognize hashes if they are preceded by `.` or `_`
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Labels: bug, cat:version-selection

#3264 Automatically merge PRs by the Scala Steward dev account
  .mergify.yml
  build.sbt
Labels: administration

#3262 Update mdoc, sbt-mdoc to 2.5.2
  project/plugins.sbt
Labels: dependency-update

#3263 Update sbt-typelevel-mergify to 0.6.5
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependency-update

#3265 Update cats-effect to 3.5.3
  project/Dependencies.scala
Labels: dependency-update

#3267 Update cron4s-core to 0.7.0
  project/Dependencies.scala
Labels: dependency-update

#3269 Update fs2-core, fs2-io to 3.9.4
  project/Dependencies.scala
Labels: dependency-update

#3241 Fail on `--vcs-*` options
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
Labels: enhancement

#3275 Update refined, refined-scalacheck to 0.11.1
  project/Dependencies.scala
Labels: dependency-update

#3278 Migrated a bunch of sbt plugins to `com.github.sbt`
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3279 Update jjwt-api, jjwt-impl, jjwt-jackson to 0.12.4
  project/Dependencies.scala
Labels: dependency-update
