Repository scala-steward-org/scala-steward, pull requests merged in 2024-11, with the labels that each got.

#3462 Update sbt-buildinfo to 0.13.0
  project/plugins.sbt
Labels: dependency-update

#3468 Update coursier, ... to 2.1.15
  project/Dependencies.scala
Labels: dependency-update

#3469 Update sbt, scripted-plugin to 1.10.5
  project/build.properties
Labels: dependency-update

#3470 Update coursier, ... to 2.1.16
  project/Dependencies.scala
Labels: dependency-update

#3466 Add JSON metadata in PRs
  modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
Labels: enhancement

#3471 Revert the base docker image back to JDK 11
  build.sbt
Labels: bug

#3472 Update sbt-buildinfo to 0.13.1
  project/plugins.sbt
Labels: dependency-update

#3473 Update coursier, ... to 2.1.17
  project/Dependencies.scala
Labels: dependency-update

#3474 Add scalafix for zio-kafka 2.9.0
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: scalafix-migration

#3481 Support Basic Auth for GitHub again
  .github/workflows/ci.yml
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/forge/ForgeAuthAlg.scala
Labels: bug

#3484 Update coursier, ... to 2.1.18
  project/Dependencies.scala
Labels: dependency-update

#3485 Update cats-effect to 3.5.6
  project/Dependencies.scala
Labels: dependency-update

#3482 Switch to codecov action v4 using a token to upload
  .github/workflows/ci.yml
  build.sbt
Labels: administration

#3483 Update commons-io to 2.18.0
  project/Dependencies.scala
Labels: dependency-update

#3489 Update coursier, ... to 2.1.19
  project/Dependencies.scala
Labels: dependency-update

#3490 Update cats-effect to 3.5.7
  project/Dependencies.scala
Labels: dependency-update
