Repository scala-steward-org/scala-steward, pull requests merged in 2024-02, with the labels that each got.

#3282 Increase default `--max-buffer-size`
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
Labels: enhancement

#3291 Update scalafmt-core to 3.8.0
  .scalafmt.conf
Labels: dependency-update

#3288 Update logback-classic to 1.5.0
  project/Dependencies.scala
Labels: dependency-update

#3289 Update coursier, ... to 2.1.9
  project/Dependencies.scala
Labels: dependency-update

#3290 Update jjwt-api, jjwt-impl, jjwt-jackson to 0.12.5
  project/Dependencies.scala
Labels: dependency-update

#3293 Update sbt-typelevel-mergify to 0.6.6
  project/plugins.sbt
Labels: dependency-update

#3294 Update sbt to 1.9.9
  project/build.properties
Labels: dependency-update

#3295 Update sbt-scoverage to 2.0.11
  modules/core/src/test/scala/org/scalasteward/core/edit/update/VersionPositionScannerTest.scala
  project/plugins.sbt
Labels: dependency-update

#3296 Un-embargo Scala 2.12.19 and 2.13.13
  modules/core/src/main/resources/default.scala-steward.conf
Labels: administration

#3298 Update scala-library to 2.13.13
  build.sbt
Labels: dependency-update

#3299 Update sbt-typelevel-mergify to 0.6.7
  project/plugins.sbt
Labels: dependency-update

#3305 Fix the merging order updates.pin
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
Labels: bug

#3308 Update logback-classic to 1.5.1
  project/Dependencies.scala
Labels: dependency-update
