Repository scala-steward-org/scala-steward, pull requests merged in 2024-10, with the labels that each got.

#3372 `scala-cli`: `using dep` and `using test.dep` directives support
  README.md
  modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
Labels: enhancement

#3356 use foldMap instead of collectFold
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
Labels: refactoring

#3361 Fix ambiguous argument 'main'
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
Labels: bug

#3349 fix azure repos targetRefName
  modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/JsonCodec.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/JsonCodecTest.scala
Labels: bug

#3284 Improve documentation for workspace ownership mismatches
  docs/running.md
  modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
  modules/docs/mdoc/running.md
Labels: enhancement

#3426 Update http4s-circe, http4s-client, ... to 1.0.0-M42
  project/Dependencies.scala
Labels: dependency-update

#3428 Update logback-classic to 1.5.9
  project/Dependencies.scala
Labels: dependency-update

#3429 Update sbt-assembly to 2.3.0
  project/plugins.sbt
Labels: dependency-update

#3430 Update sbt-ci-release to 1.7.0
  project/plugins.sbt
Labels: dependency-update

#3433 add migration for bucket4j
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3437 Update sbt-typelevel-mergify to 0.7.4
  .github/workflows/ci.yml
  modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
  project/plugins.sbt
Labels: dependency-update

#3434 Update logback-classic to 1.5.10
  project/Dependencies.scala
Labels: dependency-update

#3438 Update sbt-ci-release to 1.8.0
  project/plugins.sbt
Labels: dependency-update

#3435 Update coursier, ... to 2.1.14
  project/Dependencies.scala
Labels: dependency-update

#3440 Update logback-classic to 1.5.11
  project/Dependencies.scala
Labels: dependency-update

#3446 Update sbt, scripted-plugin to 1.10.3
  project/build.properties
Labels: dependency-update

#3447 Update sbt-scoverage to 2.2.2
  project/plugins.sbt
Labels: dependency-update

#3449 Add tasty-core to the list of scala libs
  modules/core/src/main/resources/default.scala-steward.conf
  modules/core/src/main/scala/org/scalasteward/core/data/package.scala
Labels: administration

#3452 Update sbt-ci-release to 1.9.0
  project/plugins.sbt
Labels: dependency-update

#3454 Update sbt-doctest to 0.11.0
  project/plugins.sbt
Labels: dependency-update

#3455 Update logback-classic to 1.5.12
  project/Dependencies.scala
Labels: dependency-update

#3457 Update sbt, scripted-plugin to 1.10.4
  project/build.properties
Labels: dependency-update

#3461 Update http4s-circe, http4s-client, ... to 1.0.0-M43
  project/Dependencies.scala
Labels: dependency-update

#3460 Update bcprov-jdk15to18 to 1.79
  project/Dependencies.scala
Labels: dependency-update
