Repository scala-steward-org/scala-steward, pull requests merged in 2024-12, with the labels that each got.

#3491 Update sbt, scripted-plugin to 1.10.6
  project/build.properties
Labels: dependency-update

#3488 Retract previously opened Pull Request
  docs/repo-specific-configuration.md
  modules/core/src/main/resources/default.scala-steward.conf
  modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RetractedArtifact.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RetractedArtifactTest.scala
  modules/docs/mdoc/repo-specific-configuration.md
Labels: enhancement

#3493 Update munit to 1.0.3
  project/Dependencies.scala
Labels: dependency-update

#3492 Ensure PR description is not too long
  modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
Labels: bug

#3494 Update coursier, ... to 2.1.20
  project/Dependencies.scala
Labels: dependency-update

#3495 Update http4s-circe, http4s-client, ... to 1.0.0-M44
  project/Dependencies.scala
Labels: dependency-update

#3496 Update Scala to 3.6.2
  modules/core/src/main/resources/default.scala-steward.conf
Labels: administration

#3497 Update coursier, ... to 2.1.21
  project/Dependencies.scala
Labels: dependency-update

#3498 Update cats-parse to 1.1.0
  project/Dependencies.scala
Labels: dependency-update

#3499 Update sbt-doctest to 0.11.1
  project/plugins.sbt
Labels: dependency-update

#3500 Update mdoc, sbt-mdoc to 2.6.2
  project/plugins.sbt
Labels: dependency-update

#3501 Update coursier, ... to 2.1.22
  project/Dependencies.scala
Labels: dependency-update

#3503 Update sbt-ci-release to 1.9.2
  project/plugins.sbt
Labels: dependency-update

#3504 Update http4s-jdk-http-client to 1.0.0-M10
  project/Dependencies.scala
Labels: dependency-update

#3505 Update logback-classic to 1.5.15
  project/Dependencies.scala
Labels: dependency-update

#3507 Update sbt, scripted-plugin to 1.10.7
  project/build.properties
Labels: dependency-update

#3508 Update refined, refined-scalacheck to 0.11.3
  project/Dependencies.scala
Labels: dependency-update

#3509 Update coursier, ... to 2.1.23
  project/Dependencies.scala
Labels: dependency-update

#3510 Update sbt-typelevel-mergify to 0.7.5
  .github/workflows/ci.yml
  .mergify.yml
  project/plugins.sbt
Labels: dependency-update

#3512 Use Mill script from `com-lihaoyi/mill` for the Docker image
  build.sbt
  project/Dependencies.scala
Labels: dependency-update, build

#3271 Remove `--vcs-*` options
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
Labels: enhancement, breaking-change
