Repository scala-steward-org/scala-steward, pull requests merged in 2024-05, with the labels that each got.

#3342 Update circe-generic, circe-literal, ... to 0.14.7
  project/Dependencies.scala
Labels: dependency-update

#3344 Update sbt-scoverage to 2.0.12
  modules/core/src/test/scala/org/scalasteward/core/edit/update/VersionPositionScannerTest.scala
  project/plugins.sbt
Labels: dependency-update

#3345 Update log4cats-slf4j to 2.7.0
  project/Dependencies.scala
Labels: dependency-update

#3343 Update scala-library to 2.13.14
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/data/Resolver.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Scope.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/bitbucketserver/Json.scala
Labels: dependency-update

#3346 Combine `RepoConfig` with the one taken the higher importance on the right side
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
Labels: bug

#3347 Allow 3.4.x pull request for users already on Scala Next
  modules/core/src/main/resources/default.scala-steward.conf
Labels: administration

#3351 Update coursier, ... to 2.1.10
  project/Dependencies.scala
Labels: dependency-update

#3352 Update sbt to 1.10.0
  project/build.properties
Labels: dependency-update

#3353 Update sbt-typelevel-mergify to 0.7.1
  project/plugins.sbt
Labels: dependency-update

#3350 Migrate com.sksamuel.elastic4s to nl.gn0s1s
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3354 Fix Scala 3 check
  modules/core/src/main/scala/org/scalasteward/core/data/package.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: bug, cat:version-selection

#3365 Update all munit related dependencies
  project/Dependencies.scala
Labels: dependency-update

#3367 Update cats-core, cats-laws to 2.12.0
  project/Dependencies.scala
Labels: dependency-update
