Repository scala-steward-org/scala-steward, pull requests merged in 2025-02, with the labels that each got.

#3573 Use modern syntax for `dependency:` Scalafix rules
  modules/core/src/main/resources/scalafix-migrations.conf
Labels: administration

#3571 Verify the example `.scala-steward.conf`
  build.sbt
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/VersionPattern.scala
  modules/docs/mdoc/repo-specific-configuration.md
  modules/docs/src/main/scala/DocChecker.scala
  project/Dependencies.scala
Labels: documentation

#3576 Use `RepoConfig#signoffCommits` for migrations and hooks
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/PostUpdateHook.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigration.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Labels: bug

#3579 Update scala3-library to 3.3.5
  build.sbt
Labels: dependency-update

#3581 Update cron4s-core to 0.8.2
  project/Dependencies.scala
Labels: dependency-update

#3582 Update sbt-native-packager to 1.11.1
  project/plugins.sbt
Labels: dependency-update

#3574 Disable built-in Scala CLI rules in Scalafix migrations
  modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
Labels: bug, cat:build-tool

#3584 Fix the assembly of the Docker image in CI
  build.sbt
Labels: build

#3587 Update mill-main_2.13 to 0.12.8
  project/Dependencies.scala
Labels: dependency-update

#3588 Update scalafmt-core to 3.9.0
  .git-blame-ignore-revs
  .scalafmt.conf
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
Labels: dependency-update

#3590 Update sbt-scoverage to 2.3.1
  project/plugins.sbt
Labels: dependency-update

#3591 Update scalafmt-core to 3.9.1
  .scalafmt.conf
Labels: dependency-update

#3592 Update logback-classic to 1.5.17
  project/Dependencies.scala
Labels: dependency-update
