Repository scala-steward-org/scala-steward, pull requests merged in 2025-03, with the labels that each got.

#3593 Update scalafmt-core to 3.9.2
  .scalafmt.conf
Labels: dependency-update

#3596 Update sbt, scripted-plugin to 1.10.9
  project/build.properties
Labels: dependency-update

#3597 Update sbt, scripted-plugin to 1.10.10
  project/build.properties
Labels: dependency-update

#3600 Update scalafmt-core to 3.9.3
  .scalafmt.conf
Labels: dependency-update

#3602 Update sbt-ci-release to 1.9.3
  project/plugins.sbt
Labels: dependency-update

#3603 Update scalafmt-core to 3.9.4
  .scalafmt.conf
Labels: dependency-update

#3604 Fix broken Mergify url from mergify.io to mergify.com
  docs/faq.md
  modules/docs/mdoc/faq.md
Labels: documentation

#3607 Update circe-generic, circe-literal, ... to 0.14.12
  project/Dependencies.scala
Labels: dependency-update

#3606 Update mill-main_2.13 to 0.12.9
  project/Dependencies.scala
Labels: dependency-update

#3608 Update sbt, scripted-plugin to 1.10.11
  project/build.properties
Labels: dependency-update

#3605 Add artifact migration for scala-uri
  modules/core/src/main/resources/artifact-migrations.v2.conf
Labels: artifact-migration

#3611 Update logback-classic to 1.5.18
  project/Dependencies.scala
Labels: dependency-update

#3613 Update cats-effect to 3.6.0
  project/Dependencies.scala
Labels: dependency-update

#3616 Update munit-cats-effect to 2.1.0
  project/Dependencies.scala
Labels: dependency-update

#3615 Update fs2-core, fs2-io to 3.12.0
  project/Dependencies.scala
Labels: dependency-update
