Repository scala-steward-org/scala-steward, pull requests merged in 2025-01, with the labels that each got.

#3514 Replace `deriveUnwrappedCodec` with handwritten de-/encoders
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/data/SbtVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/data/ScalaVersion.scala
  modules/core/src/main/scala/org/scalasteward/core/data/CrossDependency.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/data/PullRequestNumber.scala
  modules/core/src/main/scala/org/scalasteward/core/util/Timestamp.scala
Labels: refactoring

#3516 Update mill-main_2.13 to 0.12.5
  project/Dependencies.scala
Labels: dependency-update

#3515 Make all values in config classes optional
  modules/benchmark/src/main/scala/org/scalasteward/benchmark/UpdatesConfigBenchmark.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/ScannerAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/CommitsConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/GroupRepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/ScalafmtConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Labels: refactoring, cat:repo-config

#3517 Remove circe-generic-extras
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
  modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Resolver.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrations.scala
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactChange.scala
  modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactChanges.scala
  modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillDepParserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  project/Dependencies.scala
Labels: refactoring

#3518 Add parentheses around lambda parameters
  modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
  modules/core/src/test/scala/org/scalasteward/core/git/gitTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/stringTest.scala
Labels: refactoring

#3519 Import `MockEffOps` to fix compile errors with Scala 3
  modules/core/src/test/scala/org/scalasteward/core/application/ReposFilesLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/application/StewardAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/ForgeRepoAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubAuthAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repocache/RefreshErrorAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repocache/RepoCacheAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/ValidateRepoConfigAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsLoaderTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/HttpJsonClientTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
Labels: testing, refactoring

#3520 Annotate pattern bindings with refutable patterns
  modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillDepParserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
  modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestFrequencyTest.scala
  modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Labels: testing, refactoring

#3521 Harmonize imports for http4s and circe literals
  modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala
  modules/core/src/test/scala/org/scalasteward/core/coursier/DependencyMetadataTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/ForgeRepoTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubAuthAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinderTest.scala
Labels: refactoring

#3522 Properly indent `InitialCommandsTest`
  build.sbt
Labels: build, refactoring

#3523 Update logback-classic to 1.5.16
  project/Dependencies.scala
Labels: dependency-update

#3524 Update sbt-native-packager to 1.11.0
  project/plugins.sbt
Labels: dependency-update

#3525 Update decline to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#3526 Tweak code that uses refined so that it compiles with Scala 3
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
  modules/core/src/main/scala/org/scalasteward/core/util/string.scala
  modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/stringTest.scala
Labels: refactoring

#3527 Cross-build with Scala 3
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
  modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
  modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubAuthAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinder.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestFrequency.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/BuiltinConfigFilesTest.scala
  modules/core/src/test/scala/org/scalasteward/core/util/uriTest.scala
Labels: build, refactoring

#3528 Update munit to 1.0.4
  project/Dependencies.scala
Labels: dependency-update

#3536 Use only one variable for `mill-version` files
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
Labels: refactoring

#3539 Update coursier, ... to 2.1.24
  project/Dependencies.scala
Labels: dependency-update

#3541 Short-circuit when reading `mill-version` files
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
Labels: refactoring, cat:build-tool

#3538 Run Mill 0.11 with `--disable-ticker` instead of `--ticker false`
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
Labels: bug, cat:build-tool

#3537 Extract Mill plugins also from `build.mill{,.scala}` files
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
Labels: bug, cat:build-tool

#3261 Rework `Update` JSON encoders and decoders
  modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
  modules/core/src/test/scala/org/scalasteward/core/data/UpdateCodecTest.scala
  modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
Labels: refactoring

#3546 Use `allowOrDefault` in `UpdatesConfig.isAllowed`
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
Labels: bug, cat:repo-config

#3547 Update bcprov-jdk15to18 to 1.80
  project/Dependencies.scala
Labels: dependency-update

#3550 Update sbt-scalafmt to 2.5.4
  modules/core/src/test/scala/org/scalasteward/core/edit/update/VersionPositionScannerTest.scala
  project/plugins.sbt
Labels: dependency-update

#3551 Update scalafmt-core to 3.8.5
  .git-blame-ignore-revs
  .scalafmt.conf
  modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
Labels: dependency-update

#3553 Update sbt-typelevel-mergify to 0.7.6
  project/plugins.sbt
Labels: dependency-update

#3548 Update scala-library to 2.13.16
  build.sbt
  project/plugins.sbt
Labels: dependency-update

#3555 Update Scala to 3.6.3
  modules/core/src/main/resources/default.scala-steward.conf
Labels: administration

#3558 Update cats-core, cats-laws to 2.13.0
  project/Dependencies.scala
Labels: dependency-update

#3557 Update sbt-assembly to 2.3.1
  project/plugins.sbt
Labels: dependency-update

#3560 Rewrite `RepoCacheAlg.checkCache` as for-comprehension
  modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/repocache/RefreshErrorAlgTest.scala
Labels: refactoring

#3561 Don't exclude `warnUnusedPatVars` compiler option
  build.sbt
Labels: build

#3562 Update munit to 1.1.0
  project/Dependencies.scala
Labels: dependency-update

#3564 Support Scalafix migrations in Scala CLI builds
  modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
Labels: enhancement

#3566 Update munit-scalacheck to 1.1.0
  project/Dependencies.scala
Labels: dependency-update

#3567 Update scalafmt-core to 3.8.6
  .scalafmt.conf
Labels: dependency-update

#3568 Update sbt-typelevel-mergify to 0.7.7
  project/plugins.sbt
Labels: dependency-update

#3542 Extract dependencies from Gradle Version Catalogs
  build.sbt
  docs/repo-specific-configuration.md
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/gradle/GradleAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/gradle/gradleParser.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/gradle/package.scala
  modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/gradle/GradleAlgTest.scala
  modules/core/src/test/scala/org/scalasteward/core/buildtool/gradle/gradleParserTest.scala
  modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
  project/Dependencies.scala
Labels: enhancement, cat:build-tool

#3570 Support multiple default resolvers
  docs/help.md
  modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
  modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/gradle/GradleAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
  modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
Labels: enhancement
